### ISSUE TITLE
(3 Axis + Laser) Control in Laser Mode?

### ISSUE THREAD

**Issue by alfarosarij** [fra589/grbl-Mega-5X#10]
Hi every one,
I am designing my laser cut CNC machine. The laser head is: https://www.alibaba.com/product-detail/High-power-150W-200W-500W-auto_60467891657.html

I know that in laser mode it possible to control two axis, but I doubt is it possible to control 3axis+ Laser in laser mode of Grbl?

Please contact me with : farokhi.sarij@gmail.com

**Comment by fra589** [comment]
Hi @alfarosarij,  

As explaned in https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode, the laser mode does not affec the axis number in Grbl. It's only affec the speed control of movements. So, you can use 3 axis in laser mode.

@++;
Gauthier.

**Comment by alfarosarij** [comment]
Thank you for your reply.
