### ISSUE TITLE
All Axes are enabled and disabled even only 1 axis is running

### ISSUE THREAD

**Issue by jennisonpangan** [fra589/grbl-Mega-5X#101]
Hi. I found that the enable buttons for X, Y, Z, A, and B axes are Pins 24, 30, 38, A2, and A8, respectively. However, even if only 1 axis is running, all other axes are also enabled. Is there a way to enable only drivers that is currently running?

Need help. Thank you.

**Comment by fra589** [comment]
Hi @jennisonpangan,  
The original hardware of grbl (Arduino Uno + CNC shield) only have one enable pin for all axis. So, the initial code have been writen for this behavior.  
When the code was ported to the Arduino Mega & RAMPS shield assembly, it did not seem useful to change the enabling / disabling behavior of the motors.
Changing this may be possible, but surely very complicated, for a result which I do not really see interest.
@++;
Gauthier.
