### ISSUE TITLE
can i use b axis as extruder?

### ISSUE THREAD

**Issue by SomeTallGuy** [fra589/grbl-Mega-5X#113]
hey thank you for this project of yours. I was free and tried to make the best of my quarantine, I wanna make the 5th motor run as fast as I can, any tips or guides I could use for that. thanks in advance.

**Comment by fra589** [comment]
Hi @SomeTallGuy,  

grbl* is not designed for 3D printers, but for milling machin.
You should rather use [marlin](https://marlinfw.org/) or [repetier ](https://www.repetier.com/documentation/repetier-firmware/)  firmware.

@++;  
Gauthier.

**Comment by SomeTallGuy** [comment]
hello again, thanks for your quick reply, can I use a stepper ('b' axis) as a spindle??
and sorry for wasting your time i am not from this background.

thanks again.

**Comment by fra589** [comment]
No, you can't use stepper B as spindle since the speed will not be enough and it will not possible to have continuous rotation.
You need an hardware spindle for milling
