### ISSUE TITLE
No ability to use 5V spindle PWM

### ISSUE THREAD

**Issue by spiffyriceburner** [fra589/grbl-Mega-5X#12]
Being able to use D11 for PWM control would allow for better use of laser engravers with variable TTL.  Is there a way to do this already?

**Comment by fra589** [comment]
Hi @spiffyriceburner,  
From original [Grbl wiki](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode) :  
> Laser Mode Operation
> When laser mode is enabled, Grbl controls laser power by varying the 0-5V voltage from the spindle PWM D11 pin. 0V should be treated as disabled, while 5V is full power. Intermediate output voltages are also assumed to be linear with laser power, such that 2.5V is approximate 50% laser power. (A compile time option exists to shift this linear model to start at a non-zero voltage.)

@++;
Gauthier.
