### ISSUE TITLE
Post Processor Aspire V8

### ISSUE THREAD

**Issue by mangeewolf** [fra589/grbl-Mega-5X#122]
First thank you for your time on Ggrbl-mega-5x.
I am looking into adding a 4th axis to my DIY CNC .
Presently I use grbl on a UNO .
I have Aspire V8 with a rotary function but no Post Processor for your code.
Aspire has instructions to edit a PP [https://docs.vectric.com/docs/V10.0/Aspire/ENU/Help/form/post-processor-editing]Link(url) .
After looking at all of Aspires rotary PP I edited one.
Does the following code look like it would interface with your code??

 +================================================
+                                                
+    Aspire V8 Grbl-mega-5x Gcode   
+                                                
+================================================

 
POST_NAME = "Grbl-mega-5x(inch) (*.gcode)"
 
FILE_EXTENSION = "gcode"
 
UNITS = "INCHES"

ROTARY_WRAP_X = "A"
 
+------------------------------------------------
+    Line terminating characters                 
+------------------------------------------------
 
LINE_ENDING = "[13][10]"
 
+------------------------------------------------
+    Block numbering                             
+------------------------------------------------
 
LINE_NUMBER_START     = 0
LINE_NUMBER_INCREMENT = 10
LINE_NUMBER_MAXIMUM = 999999
 
+================================================
+                                                
+    Formating for variables                     
+                                                
+================================================
 
VAR WRAP_DIAMETER = [WRAP_DIA|A||1.4]
VAR LINE_NUMBER = [N|A|N|1.0]
VAR X_POSITION = [X|C|X|1.4]
VAR Y_POSITION = [Y|C|Y|1.4]
VAR Z_POSITION = [Z|C|Z|1.4]
VAR ARC_CENTRE_I_INC_POSITION = [I|A|I|1.4]
VAR ARC_CENTRE_J_INC_POSITION = [J|A|J|1.4]
VAR X_HOME_POSITION = [XH|A|X|1.4]
VAR Y_HOME_POSITION = [YH|A|Y|1.4]
VAR Z_HOME_POSITION = [ZH|A|Z|1.4]
 
+================================================
+                                                
+    Block definitions for toolpath output       
+                                                
+================================================
 
+---------------------------------------------------
+  Commands output at the start of the file
+---------------------------------------------------
 
begin HEADER

"T1M6"
"G17"
"G20"
"G90"
"G0 [ZH]"
"G0 G54 [XH] [YH] M3"
 

+---------------------------------------------------
+  Commands output for rapid moves 
+---------------------------------------------------
 
begin RAPID_MOVE
 
"G0 [X] [Y] [Z]"
 
 
+---------------------------------------------------
+  Commands output for the first feed rate move
+---------------------------------------------------
 
begin FIRST_FEED_MOVE
 
"G1 [X] [Y] [Z] [F]"
 
 
+---------------------------------------------------
+  Commands output for feed rate moves
+---------------------------------------------------
 
begin FEED_MOVE
 
"G1 [X] [Y] [Z]"
 
 
+---------------------------------------------------
+  Commands output for the first clockwise arc move
+---------------------------------------------------
 
begin FIRST_CW_ARC_MOVE
 
"G2 [X] [Y] [I] [J] [F]"
 
 
+---------------------------------------------------
+  Commands output for clockwise arc  move
+---------------------------------------------------
 
begin CW_ARC_MOVE
 
"G2 [X] [Y] [I] [J]"
 
 
+---------------------------------------------------
+  Commands output for the first counterclockwise arc move
+---------------------------------------------------
 
begin FIRST_CCW_ARC_MOVE
 
"G3 [X] [Y] [I] [J] [F]"
 
 
+---------------------------------------------------
+  Commands output for counterclockwise arc  move
+---------------------------------------------------
 
begin CCW_ARC_MOVE
 
"G3 [X] [Y] [I] [J]"
 
 
+---------------------------------------------------
+  Commands output at the end of the file
+---------------------------------------------------
 
begin FOOTER
 
"G0 [ZH]"
"M5"
"G0 [XH] [YH]"
"M30"``

**Comment by fra589** [comment]
Hi @mangeewolf,  
  
As Vectric Aspire is not an free (free mean as freedom) Open Source software, I don't use it, and probably never will use it.  
  
Given the price of your software, their support service should be able to help you find the solution to meet your needs.  
If not, it will not be cool on their part ... Then try on their forum.  
  
I'm sorry, but I can't help you with this question.  
  
@++;  
Gauthier.
