### ISSUE TITLE
A axis continues rotation

### ISSUE THREAD

**Issue by arlimbad222** [fra589/grbl-Mega-5X#140]
Hello friend recently I add 4th axis on my machine and I want to face of my chuck plate is there any option to run 4th axis continues . I find runout on 4th axis so if it possible I can face my chuck plate according to machine Z-axis .

**Comment by fra589** [comment]
Hi @arlimbad222,  
  
As described in the wiki : https://github.com/fra589/grbl-Mega-5X/wiki/Grbl-Configuration  
You can disable the software limit of your rotary axis by configuring the axis max travel to 0 ($133 parameter for the 4th axis).  
  
@++;  
Gauthier.

**Comment by arlimbad222** [comment]
Oh man it's solve now I manage second Arduino Uno write simple code to run stepper at constant rpm . Mount carbide tool on my z axis & turned face plate now run out was zero .
