### ISSUE TITLE
Please give Mega-5x it's own name

### ISSUE THREAD

**Issue by Robin2g** [fra589/grbl-Mega-5X#142]
May I strongly suggest that Mega-5X does NOT use the name grbl.h for its program to make it easy for people to see what version they have. grbl.h should be reserved for the name of the original 3-axis library - and even then, I think it should be changed for different versions - such as grbl-1.1n.h

I wasted hours because I had not realised I had a copy of the standard GRBL library on my PC and when trying to upload -5X the PC was using the wrong library.

I have now changed grbl.h to grbl-mega-5x.h and also changed the INIT message to "Grbl Mega 5X 1.1n ['$' for help]  ".

Not changing the library name seems to be a common failing of people who update Arduino libraries.

...R

**Comment by fra589** [comment]
No, I don't agree...  
grbl-Mega-5X is an evolution of the original Grbl, but it's Grbl.  
The failing you describe is not specific to Mega-5X, it happen to me some time ago when updating the original Grbl.  
I do not feel responsible for the mistakes of users who misread the documentation or who don't make attention for what they do.  
Today, I develop and compile grbl-Mega-5X on Linux Debian, and changing the name of any file for each version would be really annoying.  
@++;  
Gauthier.
