### ISSUE TITLE
How enable 6 axis for this code?

### ISSUE THREAD

**Issue by rodrigoevaldo** [fra589/grbl-Mega-5X#144]
Hi!

I looking the cpu_map.h file for check the I/O mapping.
I found the mapping for axis X, Y and Z. Anybody can explain me how I can enable 6 axis and check the I/O mapping for aditional axis?

**Comment by fra589** [comment]
Hi @rodrigoevaldo,  
  
Look at config.h (line 53)...  
And take a time looking the wiki : https://github.com/fra589/grbl-Mega-5X/wiki  
especially the pinout page : https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout  
  
@++;  
Gauthier.
