### ISSUE TITLE
Problem with <grbl.h>

### ISSUE THREAD

**Issue by BosniaCNC** [fra589/grbl-Mega-5X#146]
I don't understand what the problem is? Can anyone help?
Thanks
![1](https://user-images.githubusercontent.com/9415134/94846294-2ff5c580-0421-11eb-96b8-f9d1df54c58e.jpg)
![2](https://user-images.githubusercontent.com/9415134/94846304-34ba7980-0421-11eb-8e57-0122c74a9645.jpg)

**Comment by RaphaelDives** [comment]
Looks, like the "library" is not at the correct path?
Hint: the grbl-mega-5x source code goes in the Arduino library folder named "grbl".
Good luck!
Raphael

**Comment by BosniaCNC** [comment]
All right! Thanks!

**Comment by fra589** [comment]
https://github.com/gnea/grbl/wiki/Compiling-Grbl

**Comment by BosniaCNC** [comment]
#include <grbl.h>   =   #include "grbl.h"

**Comment by fra589** [comment]
If you have read the compiling doc (link I wrote few hours ago), you have put the grbl source in the standard Arduino library directory. So, the directive `#include <grbl.h>` in the file grblUpload.ino will work fine.

See the doc of the Include Syntax here: https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html  
  
@++;  
Gauthier.
