### ISSUE TITLE
Basic question: going from GRBL Mega to GRBL Mega 5X

### ISSUE THREAD

**Issue by 5axislawaetz** [fra589/grbl-Mega-5X#148]
Hello, 

I have just wired up a basic system consisting of an Arduino Mega, stepper drivers and stepper motors. 

It works fine in using GRBL Mega, the motors are moving. 

I tried the same system, with the same settings in GRBL Mega 5X. The motors are not moving. 

Here are the settings I am using:

$0=10
$1=25
$2=0
$3=0
$4=1
$5=0
$6=0
$10=1
$11=0.010
$12=0.002
$13=0
$20=0
$21=0
$22=0
$23=0
$24=25.000
$25=500.000
$26=250
$27=1.000
$30=1000
$31=0
$32=0
$100=250.000
$101=250.000
$102=250.000
$103=250.000
$104=250.000
$110=500.000
$111=500.000
$112=500.000
$113=500.000
$114=500.000
$120=10.000
$121=10.000
$122=10.000
$123=50.000
$124=50.000
$130=200.000
$131=200.000
$132=200.000
$133=200.000
$134=200.000

( the $4 setting should be 1 with the stepper drivers I am using)

When I send a command like:
G91 G0 X10
I get an "ok" from the system, but without any movement. As stated, this was working in GRBL Mega, but not with GRBL Mega 5X.

Any idea what I am doing wrong?

**Comment by fra589** [comment]
Hi @5axislawaetz,  
  
The grbl-Mega-5X version come from the grbl-Mega RAMPS configuration wich have not the same pinout than the old standard grbl-Mega one. Using the RAMPS shield require to use this spécifics pinout, but we can use this pinout directly connected on the Arduino Mega without the RAMPS bord.
  
You can found the standard pinout of the RAMPS / grbl-Mega-5X version here:  
https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout
  
@++;  
Gauthier.
