### ISSUE TITLE
Connecting to RAMPS 1.4 laser with TTL controller grbl-mega-5x ramps

### ISSUE THREAD

**Issue by skazlashop** [fra589/grbl-Mega-5X#154]
Hello everyone, help with the scheme for connecting the laser to the RAMPS 1.4 board.
TTL has 0-5 volt control, D8 pin gives 12 volts.
Which connector to connect the laser to to control the laser power and power. I have a separate power supply for the laser.
![Mostics-синий-лазерный-модуль-5-5-Вт-450-нм-детали-лазерного-гравировального-станка-TTL-модуль-лазерной](https://user-images.githubusercontent.com/74655134/99521532-93be5880-29a5-11eb-8b08-60d86231ef89.jpg)

**Comment by fra589** [comment]
Hi @skazlashop,  
  
This question being asked so very often that I have just published a new version (v1.1m) which allows to choose the spindle output used: 0-12v on D8 or 0-5v on D6 (in config.h, line 85 to 90 ).  
Download the latest version and make your choice in the config.h file.  
  
@++;  
Gauthier.
