### ISSUE TITLE
Grbl Mega on MiniRambo

### ISSUE THREAD

**Issue by garyebersole** [fra589/grbl-Mega-5X#16]
I posted a comment to an open [issue](https://github.com/gnea/grbl-Mega/issues/11) on grbl-Mega. I am trying to get the grbl-Mega clone to run on a Mini-Rambo 1.3a board (basically a single-board Arduino Mega 2560 with integrated RAMPS support). As I note in my comment, flashing with the basic grbl-Mega code with the RAMPS changes in the config.h file worked partially but your '5X' clone actually worked on my Mini-Rambo without any changes but threw a 'safety door' error.

I believe the Mini-Rambo board from [Ultimachine](https://ultimachine.com/products/mini-rambo-1-3) and the specification at [RepRap](https://reprap.org/wiki/MiniRambo) indicate a full implementation of an Arduino 2560 with support for RAMPS 1.4 but I may be mistaken. Are there any other required changes you discovered to get RAMPS 1.4 working prior to implementing your extended 5/6 axis support? I would use your implementation if I could figure out how to disable safety door alarms but I haven't been able to make that work. I commented out '#define ENABLE_SAFETY_DOOR_INPUT_PIN' in config.h but the alarm is still thrown.

Thanks for any help.

**Comment by fra589** [comment]
Hi @garyebersole,  
The Mega 2560 pin mapping of your Mini-Rambo board is not the same than an real RAMPS board...  
So, you need to compare the RAMPS mapping (see [grbl-Mega-5X pinout](https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout) and [RAMPS pinout](https://reprap.org/mediawiki/images/c/ca/Arduinomega1-4connectors.png)) to the [Mini-Rambo mapping](https://reprap.org/mediawiki/images/e/ef/MiniRambo1.3a-schematic-pg2.svg),  
Then, you will need tu update the cpu_maps.h file to adapt grbl-Mega-5X tou your hardware.
As I read rapidly the [Mini-Rambo mapping](https://reprap.org/mediawiki/images/e/ef/MiniRambo1.3a-schematic-pg2.svg), I see that the Arduino pin A12 is used for E0 extruder output... In the standard grbl-Mega-5X on RAMPS, A12 is used for safty door input... This is an explanation of your alarm status...  
I think there is many other mapping differences, so, you need to make full comparition and adapt the file cpu_map.h fot your need.  
  
@++;  
Gauthier.

**Comment by garyebersole** [comment]
Thanks @fra589!! I will spend some time carefully comparing the pin mappings and revise the cpu_map.h file to work with the Mini-Rambo board. I will post the revised map after testing on my machine.
