### ISSUE TITLE
Problem at 230400 baudrate 

### ISSUE THREAD

**Issue by NurAlif** [fra589/grbl-Mega-5X#164]
I changed the baudrate in config.h to `#define BAUD_RATE 230400`.  Then, it successfully connected with serial monitor at 230400 baudrate. I receive this line from the board `Grbl 1.1g ['$' for help]`. But, it does not respond to any commands. When I sent `$` or `$$`,  sometimes I receive `error:1` or `error:2` or `error:3` or not receiving anything from the board.

I have tested this on 2 MEGA boards, both resulting in the same result above.

**Comment by fra589** [comment]
Hi @NurAlif,  
  
You've probably exceeded the limits of what the 2560 card can do.  
A lot of literature on the net seems to indicate the reliable max limit at 115200bps. Beyond that, you have to deal with random errors.   
Go back to 115200 and everything will be fine...  
  
@++;  
Gauthier.  
P.S. The up to date version of grbl-Mega-5X is Grbl 1.1p, you have 1.1g... You should update your version.
