### ISSUE TITLE
TX and RX

### ISSUE THREAD

**Issue by luisluna2** [fra589/grbl-Mega-5X#17]
Hello friend @fra589 

Could tell me in what pin exist RX and TX in Ramps 1.4?

**Comment by fra589** [comment]
I don't understand what is exactly the question, but this it is more a RAMPS question than a grbl-Mega-5X question. So you should begin your quest on one of the master RAMPS information web site : https://reprap.org/wiki/RAMPS_1.4...

**Comment by luisluna2** [comment]
Hello then the pins for your GRBL is the SAME AT THE RAMOS MARLIN PINS TX RX?

**Comment by luisluna2** [comment]
THIS? 
![image](https://user-images.githubusercontent.com/38824145/46922535-fc20fb80-cfcf-11e8-9f60-96fb8e76a1d6.png)

**Comment by fra589** [comment]
Probably...  
Pins are hardware, not software.
