### ISSUE TITLE
Dual motor homing with 1 limit switch

### ISSUE THREAD

**Issue by d-portero** [fra589/grbl-Mega-5X#177]
I have two motors on my Y axis. I only have one limit switch on Y right now. When I home Y and the switch is enabled, only one motor stops moving. I have set the second y axis limit pin the same as the other one but it still doesn't work. Is there a way to set the second motor to stop moving as well? 

![image](https://user-images.githubusercontent.com/50592002/106342808-6842ce80-6270-11eb-8c88-a1a0864cc1e6.png)
![image](https://user-images.githubusercontent.com/50592002/106342816-7690ea80-6270-11eb-8c2f-e2506e7bbc27.png)

**Comment by RaphaelDives** [comment]
Hey,
I don’t know, if there is an educated way to achieve this, but you can just set the same port and the same pin for both axis. (I found this out accidentally... 😂)
Cheers
Raphael

edit:
Sorry, I just looked at the first part of your question, but anyway, you have to set the same PORT as well (it’s above the BIT Part)

**Comment by fra589** [comment]
Hi @d-portero,  
  
As @RaphaelDives said (thanks Raphael :smile:), you also must change the port definition in the cpu_map.h file.  
On ATMega 2560, there are 8 pins per port (one pin for each bit) and the cpu_map.h file reflect this definition: First we must define on which port is connected a functionality, then, we define on which bit.  
So, you also need to change the port definition like this:
```
  #define MAX_LIMIT_PORT_0 E
  #define MAX_LIMIT_PORT_1 J
  #define MAX_LIMIT_PORT_2 D
  #if N_AXIS > 3
    #define MAX_LIMIT_PORT_3 J
  #endif
```  
  
For more details, see the wiki here: https://github.com/fra589/grbl-Mega-5X/wiki/Pinout-mapping-in-cpu_map.h  

@++;  
Gauthier.

**Comment by d-portero** [comment]
Oh I totally missed that! Problem fixed. Thanks guys!
