### ISSUE TITLE
Additional stepper for cooling

### ISSUE THREAD

**Issue by RaphaelDives** [fra589/grbl-Mega-5X#192]
Hello @fra589,
just a crazy sunday afternoon idea: I want to add a coolant pump to my CNC. My idea was to use a peristaltic pump with a stepper motor.
Is it somehow possible to connect an additional stepper (AUX port) that just turns with a predefined feed rate when cooling is on (or maybe two different feed rates for mist and flood...)? Do you have a hint, of where to start, to implement something like this?

Or should I use an extra arduino for this task? (Or is this idea totally stupid and I should better forget about it and just use a normal pump? :D)

Thank You very much!
Cheers
Raphael

**Comment by fra589** [comment]
Hi @RaphaelDives;  
  
Like you said, it's a crazy idea :-D  
  
It seems to me very complicated, and probably very impactful in terms of performance, to add the operation of an auxiliary stepper motor. I sincerely think that it would be much better to use another Arduino board for this.  
  
@++;  
Gauthier.
