### ISSUE TITLE
Change Motors Place 

### ISSUE THREAD

**Issue by luisluna2** [fra589/grbl-Mega-5X#2]
Hello friend, one question: How can SWAP the ZAXIS motor to YAXIS motor?

I try change pins in "cpu_map.h" but when I change the pins it does not work, Not move Z and Y, in this case I use 2Y motors and 1Z motor, maybe could be best SWAP the Motors PINS.

Could tell me how?

Thank you for your coments!

**Comment by fra589** [comment]
Hi @luisluna2,

To locate the pins, the grbl firmware use 2 informations :
- The port where the pin is connected 
- The bit used on the port (each port of the controler control 8 pins, one per bit)

So, to swap the Y and Z motors, you need to swap between the axis 1 and 2 :
- STEP_PORT and STEP_BIT
- DIRECTION_PORT and DIRECTION_BIT
- STEPPER_DISABLE_PORT and STEPPER_DISABLE_BIT

For your need :
```
  #define STEP_PORT_2 F
  #define STEP_PORT_1 L

  #define STEP_BIT_2 6  // Y Step - Pin A6
  #define STEP_BIT_1 3  // Z Step - Pin D46

  #define DIRECTION_PORT_2 F
  #define DIRECTION_PORT_1 L

  #define DIRECTION_BIT_2 7 // Y Dir - Pin A7
  #define DIRECTION_BIT_1 1 // Z Dir - Pin D48

  #define STEPPER_DISABLE_PORT_2 F
  #define STEPPER_DISABLE_PORT_1 K

  #define STEPPER_DISABLE_BIT_2 2 // Y Enable - Pin A2
  #define STEPPER_DISABLE_BIT_1 0 // Z Enable - Pin A8
```

@++;
Gauthier.

**Comment by luisluna2** [comment]
I will try!, but I already had (I remember), Maybe I have a mistake!, I will tell in few minutes :1st_place_medal:

**Comment by luisluna2** [comment]
Ummmm not work :C

**Comment by luisluna2** [comment]
OKAY DONE!, Neeed change like this (PORT, BIT and letter or number):

 `#define STEP_PORT_2 L //F`
  `#define STEP_PORT_1 F //L`
``
  `#define STEP_BIT_2 3 //6  Y Step - Pin A6`
  `#define STEP_BIT_1 6 //3  Z Step - Pin D46`
``
  `#define DIRECTION_PORT_2 L //F`
  `#define DIRECTION_PORT_1 F //L`
``
  `#define DIRECTION_BIT_2 1 //7  Y Dir - Pin A7`
  `#define DIRECTION_BIT_1 7 //1  Z Dir - Pin D48`
``
  `#define STEPPER_DISABLE_PORT_2 K //F`
  `#define STEPPER_DISABLE_PORT_1 F //K`
``
  `#define STEPPER_DISABLE_BIT_2 0 //2  Y Enable - Pin A2`
  `#define STEPPER_DISABLE_BIT_1 2 //0  Z Enable - Pin A8`

Thank you for you Reply :)

Now, I wanna move the machine (5 axis) with the 128x64 LCD (Like Marlin), you could you tell me where to start? (I'm not a programmer) :+1:

**Comment by luisluna2** [comment]
OKAY DONE!, Neeed change like this (PORT, BIT and letter or number):

 ```
#define STEP_PORT_2 L //F
  #define STEP_PORT_1 F //L

  #define STEP_BIT_2 3 //6  Y Step - Pin A6
  #define STEP_BIT_1 6 //3  Z Step - Pin D46

  #define DIRECTION_PORT_2 L //F
  #define DIRECTION_PORT_1 F //L

  #define DIRECTION_BIT_2 1 //7  Y Dir - Pin A7
  #define DIRECTION_BIT_1 7 //1  Z Dir - Pin D48

  #define STEPPER_DISABLE_PORT_2 K //F
  #define STEPPER_DISABLE_PORT_1 F //K

  #define STEPPER_DISABLE_BIT_2 0 //2  Y Enable - Pin A2
  #define STEPPER_DISABLE_BIT_1 2 //0  Z Enable - Pin A8
`````
Thank you for you Reply :)

Now, I wanna move the machine (5 axis) with the 128x64 LCD (Like Marlin), you could you tell me where to start? (I'm not a programmer) :+1:

**Comment by LukeBonathan** [comment]
Can you share your updated hex file please?

**Comment by luisluna2** [comment]
HELLO @LukeBonathan  SO SORRY FOR NOT REPLY!!!, SURE, WAIT FOR TOMORROW AND I WILL UPLOAD THE FILE!

**Comment by luisluna2** [comment]
Dear @fra589  one important question:

how can modify for example: 
 #define STEP_BIT_1 6 //3  Z Step - Pin D46 to  #define STEP_BIT_1 6 //3  Z Step - "Pin D48"
???

I need modify some DXX pins to others DXX pins, in what file found this?

**Comment by luisluna2** [comment]
hi @LukeBonathan  what axis need clone friend?

**Comment by fra589** [comment]
Hi @luisluna2,

you need to modify both #define STEP_BIT_1 and STEP_PORT_1 in cpu_map.h...  

First, search for "mega 2560 pinout" on google images. Then you will found this type of picture :  
https://www.14core.com/wp-content/uploads/2015/06/ATMEGA-2560-Pin-Out-Diagram.png  
or this :  
https://www.bitsandparts.eu/documentation/299/ARDUINO.Mega.Pinout.Diagram.png

By default, the third axis (AXIS_2) is on D46
In thoses pictures, you can see that the pin D46 is on port PL3 of Arduino board. So, the port definition in cpumap.h is :  
`#define STEP_PORT_2 L`  
`#define STEP_BIT_2 3  // Z Step - Pin D46`  
  
if you want to change to D51 (for example), you will find on the picture that is it on Arduino's port PB2. So, change the definition to :    
`#define STEP_PORT_2 B`  
`#define STEP_BIT_2 2  // Z Step - Pin D51`  
  
That's all :)
@++;
Gauthier.

**Comment by luisluna2** [comment]
WOW, for my this is very complicated haha.

this is that I wanna add:

4 Relays OutPuts 0V-5V with this:

[http://www.cnc-club.ru/forum/viewtopic.php?f=151&t=7459&p=260998#p260998](url)

and Finally need know how modify this:

М62 (MEGA2560 Digital Pin 37) включает М63 отключает исполнительный механизм
М64 (MEGA2560 Digital Pin 36) включает М65 отключает...
М66 (MEGA2560 Digital Pin 35) включает М67 отключает...
М68 (MEGA2560 Digital Pin 34) включает М69 отключает...

For have this:

![relay](https://user-images.githubusercontent.com/38824145/44681605-adf76f00-aa06-11e8-8587-22e933faad91.png)
