### ISSUE TITLE
Grbl functions without serial.

### ISSUE THREAD

**Issue by Carlosan99** [fra589/grbl-Mega-5X#213]
Hello,
I need coordinated movement with acceleration to make straight lines (G0 commands).
Is there any way to include only this function in an  existing sketch?
Something like: motors.move(x,y,z,a,b)

Thanks!

**Comment by RaphaelDives** [comment]
Hey,
I won’t say that’s impossible, but that’s not what’s GRBL for. Plus GRBL has nothing to do with Arduino IDE (it’s just one convenient  way to upload it to an Arduino).
For such „hardcoded“ case, I would search for some Arduino libraries like AccelStepper.
But I may be wrong. 😉

Anyway I would just use a second (tiny) Arduino as a serial sender… 😉
Cheers
Raphael
