### ISSUE TITLE
implementation of the PS-ON pin

### ISSUE THREAD

**Issue by erathos** [fra589/grbl-Mega-5X#22]
Hello, I hope that you will have the time to finalize your work because we are many interested in the CNC 5 axis CNC using GRBL. May I suggest that you implement the use of the mega D12 pin (PS-ON of the Ramps) by the command M80 / M81 as it is the case for Marlin? This for the control of an ATX power supply for the axis motors or the power supply of the spindle via an SSR relay ...
Thank you for your great work

**Comment by fra589** [comment]
Hi,
This idea is not so bad, but real CNC machining need more power than an ATX can provide...  
So I think this functionality is not realy usefull.
I prefer to optimize the code for stability, performance and multiaxis geometric functionality.
@++;
Gauthier.
