### ISSUE TITLE
Dual Y Axis

### ISSUE THREAD

**Issue by judyhusin** [fra589/grbl-Mega-5X#220]
I'm using Mega 5x 1.2d version, using dual Y axis with one stepper driver for each Y axis. Recently i noticed my dual Y axis has difference in step per mm, for example Y1 move 100 cm and Y2 only move 99.5 cm. So i tried to adjust the steps/mm differently $101=10, $103=10.065. But when i do that, the gcode runs ok only for 500 line and then comes alarm 4, or just hang, and the movement stops and feed rate become 2147483647 or X, Y and Z 2147483647 . Is it normal behavior that we can't adjust different step/mm for cloned axis? Because when i put the same value in $101 and $103, it runs smoothly till the end of gcode line.

**Comment by fra589** [comment]
Hi @judyhusin,  
  
You need to have exactly same parameters (step/unit, maximum travel, speed and acceleration) for cloned axes, as somepart of the code can only use one parameter for computing and planing movements and force this movement to the cloned axis.  
  
This mean you need to have the same hardware for cloned axes.

Perhaps I need to add some verifications in the code and throw an throw an error in case of wrong cloning axis config...

@++;
Gauthier.
