### ISSUE TITLE
Dual y axis speed issue

### ISSUE THREAD

**Issue by muhammadelmogy** [fra589/grbl-Mega-5X#222]
I have ramps 1.4 with 4 DRV drivers
All axises are 1/16 in settings
Also all axises are set 1/16 in hardware
Cloned Y on A axis
Connected second Y on E0 position
Y1 is running normal but Y2 is running as if it is 1/4 microstep which makes it run much slower than Y1
I have confirmed this by setting microstep for 
E0 in hardware to 1/4 and it was running the same speed as Y1!

**Comment by RaphaelDives** [comment]
I think you should post you $$ output... ;)

**Comment by muhammadelmogy** [comment]
terminal output
$0=10 (Step pulse time, microseconds)
$1=255 (Step idle delay, milliseconds)
$2=0 (Step pulse invert, mask)
$3=3 (Step direction invert, mask)
$4=0 (Invert step enable pin, boolean)
$5=0 (Invert limit pins, boolean)
$6=0 (Invert probe pin, boolean)
$10=1 (Status report options, mask)
$11=0.020 (Junction deviation, millimeters)
$12=0.002 (Arc tolerance, millimeters)
$13=0 (Report in inches, boolean)
$20=1 (Soft limits enable, boolean)
$21=0 (Hard limits enable, boolean)
$22=1 (Homing cycle enable, boolean)
$23=0 (Homing direction invert, mask)
$24=500.000 (Homing locate feed rate, mm/min)
$25=2000.000 (Homing search seek rate, mm/min)
$26=250 (Homing switch debounce delay, milliseconds)
$27=2.000 (Homing switch pull-off distance, millimeters)
$30=20000 (Maximum spindle speed, RPM)
$31=0 (Minimum spindle speed, RPM)
$32=0 (Laser-mode enable, boolean)
$100=53.330 (X-axis travel resolution, step/mm)
$101=160.000 (Y-axis travel resolution, step/mm)
$102=800.000 (Z-axis travel resolution, step/mm)
$103=40.000
$110=7200.000 (X-axis maximum rate, mm/min)
$111=7200.000 (Y-axis maximum rate, mm/min)
$112=400.000 (Z-axis maximum rate, mm/min)
$113=7200.000
$120=400.000 (X-axis acceleration, mm/sec^2)
$121=400.000 (Y-axis acceleration, mm/sec^2)
$122=200.000 (Z-axis acceleration, mm/sec^2)
$123=400.000
$130=300.000 (X-axis maximum travel, millimeters)
$131=330.000 (Y-axis maximum travel, millimeters)
$132=90.000 (Z-axis maximum travel, millimeters)
$133=798.000

**Comment by RaphaelDives** [comment]
Hi @muhammadelmogy,
there are several settings, that are axis related.
You can see this e.g. at $100 to $103, where $100 is X, $101 is Y $102 is Z AND $103 is (your cloned axis) A/Y.
So the setting for $101 and $103 have to be the same.
The same is true for $111/$113, $121/$123 and $130/133.
I'm pretty shure this will solve your problems. ;)

Good luck
Raphael

By the way... $101=160 and $103=40 is 1/4 as you found out correctly ;)

**Comment by muhammadelmogy** [comment]
Well, it is really weird, I couldn't find anywhere the value 40 being used in the source code especially  I have changed all the values in defaults.h
Anyway, it is working now
