### ISSUE TITLE
MKS GEN-L V1.0 D42 end-stop

### ISSUE THREAD

**Issue by wollo-fpv** [fra589/grbl-Mega-5X#223]
Hello,

I use a MKS GEN-L V1.0 on my laser cnc table.
I have cloned the Y axis.
For homing I have disabled the Z axis.
Homing direction as well working direction of all axis are good.
I have connected end-stop on X-min and Y(0)-min, as well Y(1)(clone) on D42.
The limit-switches have 3 wires +-S.
As soon I start homing X is homing and then Y(0) and Y(1) starting to home.
When Y(0) trigger, the stepper of Y(0) stop to work.
But if Y(1) is trigger the stepper don't stop moving.
I have replaced already the end-stop. But still I grbl don't react on the switch.

https://img.staticbg.com/images/oaupload/banggood/images/B8/0F/01cf2700-fdac-43ce-905b-70f17754f424.jpg

On the MKS GEN-L the D42 is inside the TFT port....

What do I need to do

Kind regads,

Wolf

**Comment by RaphaelDives** [comment]
Hello @wollo-fpv,
First, I would check if the limit switch is reported correctly.
I think it was the "?" command and I think the cloned axis limit switch should report as YY.

Second - double check your config... D42 should be PL7 (Don't forget to set the right port!)
I would also check if the PL7 is not used for any other function.
(So maybe try another pin for testing?)

Third, to make a more educated guess, you should post some more information - I would guess the cpu_map, your config and your "$$" output... :)

Cheers
Raphael

**Comment by wollo-fpv** [comment]
Thx,
@RaphaelDives 
I did not change  cpu_map.h until now.
What do you mean with "D42 should be PL7"
I attached the config.h and cpu_map
Kind regards
Wolf


[cpu_map.h.txt](https://github.com/fra589/grbl-Mega-5X/files/7435340/cpu_map.h.txt)
[config.h.txt](https://github.com/fra589/grbl-Mega-5X/files/7435341/config.h.txt)

**Comment by wollo-fpv** [comment]
Thx,
@RaphaelDives
Understood .... :) :)
Will check it...!

**Comment by wollo-fpv** [comment]
Hello,
Issue can be closed!
My mistake.. :(
Have not used right pin, like Raphael already guessed ...
@RaphaelDives, thank you

Kr
Wolf

**Comment by RaphaelDives** [comment]
You're welcome! 😊 
Cheers Raphael
