### ISSUE TITLE
Laser control Pinout

### ISSUE THREAD

**Issue by chappy1978** [fra589/grbl-Mega-5X#234]
How do I change the pin for the laser control? I see that it is setup for D6 or D8 but Im working on converting the pinout to work with an Ultimaker board and it uses D7 for laser control.

**Comment by fra589** [comment]
Hello @chappy1978,  
  
You need to change it in the cpu_map.h file and change to:  
```
#define SPINDLE_OCR_REGISTER OCR4B
#define SPINDLE_COMB_BIT COM4B1
#define SPINDLE_PWM_BIT 4
```
I don't make hardware verify, but it should work...
Tell me if this is ok.  
  
@++;  
Gauthier.

**Comment by chappy1978** [comment]
Thanks for the help.
