### ISSUE TITLE
A axis not working.

### ISSUE THREAD

**Issue by jodougie2812** [fra589/grbl-Mega-5X#238]
Hi I'm very new to this. A new hobby in retirement so please be patient with me.
I'm building a 4 axis CNC using Mega5x on an arduino mega wIth a ramps1.4. I'm controlling this with GRBLGRU
I've got everything connected. X Y Z works well but I get no response on A axis. I'm wondering if I need to alter anything in the code to switch A drive on.
Im stuck on this Any help is appreciated.

**Comment by fra589** [comment]
Hi @jodougie2812,  
  
Without any other info, I will be difficult for me to help you.
Please, post the result of the `$I` and `$$` Grbl commands...
  
@++;
Gauthier.

**Comment by jodougie2812** [comment]
Thanks for your reply.
I seem to have solved the A axis issue.
It was a bad connection.
Thankyou for your help

**Comment by jodougie2812** [comment]
Can I replace a spindle with a laser please

**Comment by RaphaelDives** [comment]
Yes, you can replace the spindle with a laser... ;)
I would go for the laser mode: https://github.com/fra589/grbl-Mega-5X/wiki/Laser-Mode
Anyway, I think you should open a new issue when you encounter any problems.
Cheers
Raphael

**Comment by jodougie2812** [comment]
Thank you for your reply
I will teach myself how to use this facility
😆
