### ISSUE TITLE
G code doesnt run

### ISSUE THREAD

**Issue by PJAlves01** [fra589/grbl-Mega-5X#249]
Hi everyone!
I changed my controller from a UNO to a MEGA.
The ONLY thing i did was clone the X and Y Axis.
I can jog very well the machine on CNCjs.
But when i Run the g code (that worked on uno with grbl) it just doesnt work. No errors, nothing. Just doesnt move

Help please, i dont know what to do more.

**Comment by fra589** [comment]
Hi @PJAlves01,  
  
grbl-Mega-5X work perfectly well for me and many peoples.  
Without your detailed configuration information ($$ result), exact grbl-Mega-5X version ($I result) and the incriminated GCode file, it will be very difficult to understand what happen to you...  
  
@++;  
Gauthier.

**Comment by PJAlves01** [comment]
> $$
$0=10 (Step pulse time, microseconds)
$1=254 (Step idle delay, milliseconds)
$2=0 (Step pulse invert, mask)
$3=0 (Step direction invert, mask)
$4=0 (Invert step enable pin, boolean)
$5=0 (Invert limit pins, boolean)
$6=0 (Invert probe pin, boolean)
$10=1 (Status report options, mask)
$11=0.020 (Junction deviation, millimeters)
$12=0.002 (Arc tolerance, millimeters)
$13=0 (Report in inches, boolean)
$20=0 (Soft limits enable, boolean)
$21=0 (Hard limits enable, boolean)
$22=1 (Homing cycle enable, boolean)
$23=0 (Homing direction invert, mask)
$24=100.000 (Homing locate feed rate, mm/min)
$25=500.000 (Homing search seek rate, mm/min)
$26=250 (Homing switch debounce delay, milliseconds)
$27=5.000 (Homing switch pull-off distance, millimeters)
$30=12000 (Maximum spindle speed, RPM)
$31=550 (Minimum spindle speed, RPM)
$32=0 (Laser-mode enable, boolean)
$100=16.670 (X-axis travel resolution, step/mm)
$101=16.670 (Y-axis travel resolution, step/mm)
$102=400.000 (Z-axis travel resolution, step/mm)
$103=16.670
$104=16.670
$110=750.000 (X-axis maximum rate, mm/min)
$111=750.000 (Y-axis maximum rate, mm/min)
$112=750.000 (Z-axis maximum rate, mm/min)
$113=750.000
$114=750.000
$120=50.000 (X-axis acceleration, mm/sec^2)
$121=50.000 (Y-axis acceleration, mm/sec^2)
$122=50.000 (Z-axis acceleration, mm/sec^2)
$123=50.000
$124=50.000
$130=400.000 (X-axis maximum travel, millimeters)
$131=200.000 (Y-axis maximum travel, millimeters)
$132=200.000 (Z-axis maximum travel, millimeters)
$133=400.000
$134=200.000

> $I
[VER:1.2d.20210930:]
[AXS:5:XYZXY]
[OPT:VNMGH,35,255,16]

**Comment by PJAlves01** [comment]
Thank you for your reply.
Neither G-code from Aspire or Fusion 360 works. (Grbl post processor)
In CNCjs it appears to be moving, but the steppers just turn off and dont move

**Comment by PJAlves01** [comment]
[12.txt](https://github.com/fra589/grbl-Mega-5X/files/8003840/12.txt)

**Comment by RaphaelDives** [comment]
Hey,
I maybe had a similar problem with Cambam. It would load the gcode, i could start it and then my bcnc said "done". I found out it was an M command in the fileheader... Since when I remove the header of my files, the whole code runs without error. (But maybe this is a bcnc error... ;) 
Cheers
Raphael

PS: Can you just try out some simple G Commands? Do they work?

**Comment by PJAlves01** [comment]
That is from Aspire, which worked very well on Uno.
I really dont know what is happening (I did $RST=*)

**Comment by PJAlves01** [comment]
> 

No M commands in here :/

**Comment by fra589** [comment]
Hi @PJAlves01,  
  
Your config and GCode file seams to be good...  
Your file run normally on my machine with full moving...  
Are you shure your Grbl is not in "Check gcode mode" (result of $C command) ?  
Search on the CNCjs side or perhaps you can issue a test with another Grbl sender...  
  
@++;  
Gauthier.

**Comment by PJAlves01** [comment]
Thank you for tacking your time to help me!

I really dont know what is happening. I have tried sending with UGS and the same thing happens. Its so strange.

That must not be the case, the Z Axis moves up and then everything shuts down (but the g code keeps running on CNCjs)

**Comment by PJAlves01** [comment]
Next thing to try is using my other PC. Really getting out of options here :/

**Comment by fra589** [comment]
Do you confirm that you use standard Arduino Mega with RAMPS shield ?
If this is not a RAMPS shield, perhaps you have to adapt the pinout...
https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout

**Comment by PJAlves01** [comment]
Im not using Ramps but everything is connected correctly. (Im using TB6600 drivers) 
I can manually move the machine on CNCjs.

**Comment by PJAlves01** [comment]
I had Stepper enable connected to spindle enable. Maybe i need glasses :/
Sorry to bother you.
Thank you for your time!
