### ISSUE TITLE
Setting up a z axis touch plate - which pin do I use?

### ISSUE THREAD

**Issue by MarkEMark2** [fra589/grbl-Mega-5X#260]
I would like to add a z axis touch plate to properly set my z axis tool to the surface of the cutting project. Which pin would I connect the touch plate to on the Arduino (or Arduino mega 5x)? My homing now works on my 3 axis machine and this still needs to be figured out.

I think this is the last of my set up issues. Thank you for all of the support!

**Comment by fra589** [comment]
Hello @MarkEMark2,  
  
It is the Probe function that meets your need. So you have to use the Probe pin.  
see https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout.  
  
@++;  
Gauthier.
