### ISSUE TITLE
THC Support

### ISSUE THREAD

**Issue by DexasElectronics** [fra589/grbl-Mega-5X#268]
Hello. By any chance there are any plans for any kind of THC support? I know that whole THC implementation might be really problematic, but it would be great to at least have inputs for "Z+" and Z-" which could be controlled by separate hardware. Issue is, if you are controlling torch height by a separate hardware, grbl doesnt know the current position of the torch on Z axis, so there will be problems when grbl will try to move Z axis because its actual position will be different from what grbl thinks it is. (it is possible to somewhat counteract this by moving torch to exact position after cutting is over using external hardware, but then there might be another issue that grbl will try to move the torch at the same time as external hardware, which will still result in skipped steps, or gcode has to have a delay after each cut to allow external hardware to move back to proper height, which complicates gcode itself). If we would have inputs Z+ and Z-, external hardware could simply send signals so grbl itself can move the axis up and down, without loosing axis position. This theoreticly could be done by sending gcode commands, but issue is that you cant execute axis movement command while grbl is executing another command, like cutting and so.

**Comment by fra589** [comment]
Hi @DexasElectronics,  
  
I'm afraid that's not possible without completely changing Grbl's operating model.  
Indeed, Grbl does not process move orders as is in a continuous stream. The movements are broken down into motor steps unit pulses. The algorithm calculates, according to the speed and acceleration parameters, the moment when the pulse must be sent to the motor, then this is sent to the planner buffer.  
It is the timer interrupt processing which is responsible for recovering the movements pending in the planner and sending them at the right time to the engines.  
Adding a Z+ or Z- function to modify the Z value during the movement would require intervening on the movements already calculated and redoing all the buffer calculations to guarantee the speed and acceleration processing.  
It seems impossible to me without rewriting all Grbl.  
  
A solution could consist in the use of an additional independent axis controlled by a 2nd Grbl which would react in real time to the height of the torch.  
The position of the Z axis would then always be known as the sum of the Z axis and the additional axis of the 2nd Grbl.  
  
@++;  
Gauthier.
