### ISSUE TITLE
not an issue (state of things)

### ISSUE THREAD

**Issue by walterwissmann** [fra589/grbl-Mega-5X#28]
Hello all,

After i have finished my MEGA-Shield i can help to do many tests for grbl with more axis ;)
Now i am here:
![grbl5x_i](https://user-images.githubusercontent.com/42293697/51677090-ccbf5900-1fd8-11e9-96b9-6ee98e8a0c73.jpg)

The shield has the pin-layout from John as wrote here up to 6-aixsis:
https://github.com/fra589/grbl-Mega-5X/issues/26

Then it should work in this housing:
![p1120833](https://user-images.githubusercontent.com/42293697/51677348-a221d000-1fd9-11e9-864e-73b3db59ac20.JPG)

br
Walter

**Comment by walterwissmann** [comment]
Hi,

The shield are done for 6-axis ;)

![mega_shield](https://user-images.githubusercontent.com/42293697/52244148-8de4a980-28dc-11e9-8a71-4fc3614c7b07.jpg)
![mega_shield_back](https://user-images.githubusercontent.com/42293697/52244154-91783080-28dc-11e9-9e1a-eaab8d682e89.jpg)

It has all the connections to the spindle potetialfree also the PWM and OverCurrent Stop ;):
![mega_shield_spindel](https://user-images.githubusercontent.com/42293697/52244504-36473d80-28de-11e9-982b-85f2ef9698d5.jpg)

Many connectors to the front panel:
![mega_shield_panel_ssr](https://user-images.githubusercontent.com/42293697/52244528-5971ed00-28de-11e9-8752-8d6a8faf2c96.jpg)

All Limits connectors have Probe, 5V, 12V
![mega_shield_limits_probe](https://user-images.githubusercontent.com/42293697/52244576-93db8a00-28de-11e9-81dc-858c971a465d.jpg)

And here the connections to the Stepper driver / Servos:
![mega_shield_stepper](https://user-images.githubusercontent.com/42293697/52244848-a1ddda80-28df-11e9-9041-f380e00ae813.jpg)

If anybody have an interest, let me know.

BR
Walter

**Comment by walterwissmann** [comment]
sorry, opened now ;)

**Comment by walterwissmann** [comment]
How can i reopen it?

**Comment by fra589** [comment]
Wow ! Amazing job :clap: :clap: :clap:

**Comment by walterwissmann** [comment]
Thanks Gautier,

The plan is i will give the gerber files to a professional to let make the PCB. Then i will test them. I think in around 10 days i can say is the PCB ok or not ;)

The shield has the pin-layout from John as wrote here up to 6-aixsis:
#26
John sayes:
` I have completed a round of testing and revised the cpu map "CPU_MAP_2560_6X" of my fork to better organize the wiring. I changed it so the step, dir, and enable output pins are adjacent and in line per each stepper driver. See rev A of the pin layout document for details
[grbl-Mega-5X_wiring8axis_RevA.pdf](https://github.com/fra589/grbl-Mega-5X/files/2757778/grbl-Mega-5X_wiring8axis_RevA.pdf)

Additionally, I have also added six hard limit switches with pin change interrupt.
`
I think that is  good way.

BR
Walter

**Comment by walterwissmann** [comment]
Hi,
a little update:

![p1120870](https://user-images.githubusercontent.com/42293697/53049737-ffedee80-3497-11e9-9789-30fdb4cdc2cd.JPG)

I think to the weekend it runs ;)

BR
Walter

**Comment by n0th1n6** [comment]
Just subscribing here. When it work, do you have a plan to sell boards?

**Comment by jflapao** [comment]
If you sell the board, what the price?
I'm interest in one board for mega

José Lapão

A qua, 20/02/2019, 05:21, Noli Rafallo <notifications@github.com> escreveu:

**Comment by walterwissmann** [comment]
Ok, we see this board has potential.

But all the thinks about this board can i and / or fra589 not do alone ;)
We need help.

BR
Walter

**Comment by walterwissmann** [comment]
Hi,
 i have today done an addition to the FC.
This addon let me switch between automatic and hand steering the FC.
Also it has plugs for all cables and an On-Off-Switch.
![p1120883](https://user-images.githubusercontent.com/42293697/53264356-aaa21f00-36db-11e9-9815-a851803e5175.JPG)

All the connections to the MEGA-Shield and the AddOnFC i have tested and the lines are ok :)
![p1120885](https://user-images.githubusercontent.com/42293697/53264609-50ee2480-36dc-11e9-84bc-d32c6733bd1e.JPG)

BR
Walter

**Comment by walterwissmann** [comment]
Hi,
It is not ready assembled yet, but i can say all the parts on the PCB and the AddOnFC workes great together :)
Here the curve of the PWM to 0-10V converter:
I have to linearise it a little bit more... but for now and for me it looks good. 
![image](https://user-images.githubusercontent.com/42293697/53306182-3a85cb80-388a-11e9-9667-10d0703d76d9.png)

Could it be i found a bug in the grbl software?
I could not switch the revolution direction directly of the spindle from CW to CCW, but from CCW to CW is ok

CW to CCW:
M3 S10000
M4 S9000
M5
M4

Then CCW to CW:
M3 s10000

BR
Walter

**Comment by fra589** [comment]
Hi Walter,

> Could it be i found a bug in the grbl software?
I could not switch the revolution direction directly of the spindle from CW to CCW, but from CCW to CW is ok

For me, switch from CW to CCW to CW... work well :  
```
Grbl 1.1i ['$' for help]  
[MSG:'$H'|'$X' to unlock]  
[VER:1.1i.20181204:]  
[AXS:5:XYZAB]  
[OPT:VNMH,35,255]  
ok  
ok  
$X  
[MSG:Caution: Unlocked]  
ok  
M3  
ok  
M4  
ok  
M3  
ok  
M5  
ok

```

@++;
Gauthier.

**Comment by walterwissmann** [comment]
Hi Gauthier,
Hmm, nice to hear this... :) I have to search ;)

BTW: 
See at the PWM-Diagram above.
Would be nice, we could lineryse the PWM with software ;)

BR
Walter

**Comment by fra589** [comment]
Hi Water,
Grbl software already have a linear model adjust function for PWM spindle :smile:   
See ENABLE_PIECEWISE_LINEAR_SPINDLE in config.h (parameters from line 658 to 680),  
There is a documented Python script to calculate values in doc/scipt/fit_nonlinear_spindle.py.
@++;
Gauthier.

**Comment by walterwissmann** [comment]
Hi Gauthier.

Wow, thanks a lot! :-)

BR
Walter
