### ISSUE TITLE
Error in digital_control.c

### ISSUE THREAD

**Issue by LeeRossCritchlow** [fra589/grbl-Mega-5X#283]
line 183 reads #ifdef INVERT_DIGITAL_OUTPUT_PIN_0 should be  #ifdef INVERT_DIGITAL_OUTPUT_PIN_1.

**Comment by fra589** [comment]
Hi @LeeRossCritchlow,  
  
Thanks for report! Joys of copy/paste :-)
  
I just pushed the correction in version build 20220826.

@++;
Gauthier.
