### ISSUE TITLE
Some new grbl settings don't have a name (comment) on the grbl console

### ISSUE THREAD

**Issue by zalexzperez** [fra589/grbl-Mega-5X#289]
![image](https://user-images.githubusercontent.com/38706594/189523663-026a9a68-26a2-4ed5-8a10-b74cea4a02b7.png)

$35, $36, $103, $113,$123, $133 don't have a name.

Basically, the new optional PWM output on D9 and the extra axes.

Also, is there a way to correct the reported axes names? My machine has 4-linear axes: cloned x and y, but seeing "Z" for my third axis (cloned X) and no name for the 4th axis (cloned Y) is quite ugly and confusing at times.

I'm using gSender to control my machine, nice interface with firmware tool, but unfortunately it doesn't even show those unnamed parameters.

**Comment by fra589** [comment]
Hi @zalexzperez,  
  
Grbl doesn't report those comments by itself. The comments are added by the GCode sender, your sender (gSender) don't know those new settings.
You need to ask the gSender programmer to add it.
Definitions of parameters are in the file: [doc/csv/setting_codes_en_US.csv](https://github.com/fra589/grbl-Mega-5X/blob/edge/doc/csv/setting_codes_en_US.csv)
New interface functionalities of grbl-Mega-5X are up to date in the wiki: https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-v1.2-interface

@++;  
Gauthier.
