### ISSUE TITLE
Ability to specifiy endstop offset for cloned axis

### ISSUE THREAD

**Issue by zerg32** [fra589/grbl-Mega-5X#29]
Thanks for great software. I'm using it for my MPCNC with cloned X and Y axis. I have dual motors and dual endstops on both X and Y. I'd like to have a way to set the endstop offset to perform auto squaring. For example of X1 endstop is 0.5mm further then X2 endstop it will be great to be able to tell grbl to move X1 motor additional 0.5mm after homing.

**Comment by fra589** [comment]
Hi @zerg32,
It would be much more complicated to realize this than to place a mechanical adjustment system on the end stops.
@++;
Gauthier.

It's not because it's already done that there's nothing left to do.
