### ISSUE TITLE
GRBL Plotter Commands

### ISSUE THREAD

**Issue by jbaker1311** [fra589/grbl-Mega-5X#304]
Good afternoon, I'm trying to work out how to get my air assist working with grbl.
https://github.com/svenhb/GRBL-Plotter/issues/313
I've pinned them to D16 & D17 which need a signal to say on and off.
Previously I had them on coolant and mist but I needed them individually to turn off.
Now I'm working the commands to get them to work, any advice or answers?

Cheers Jacob

**Comment by fra589** [comment]
Hi @jbaker1311,  
  
Standard Grbl-Mega-5X digital output pinout is : D16 = digital output 0 and D17 = digital output 1.  

As described in http://linuxcnc.org/docs/html/gcode/m-code.html#mcode:m62-m65:  
- M62 P- - turn on digital output synchronized with motion. The P- word specifies the digital output number.
- M63 P- - turn off digital output synchronized with motion. The P- word specifies the digital output number.
- M64 P- - turn on digital output immediately. The P- word specifies the digital output number.
- M65 P- - turn off digital output immediately. The P- word specifies the digital output number.  

So, for example: to turn D16 ON, synchronized with motion, use the GCode command:  
`M62 P0`
to turn it of:  
`M63 P0`
  
Use P1 for D17

@++;  
Gauthier.

**Comment by jbaker1311** [comment]
Thanks for the swift reply, specifically I can't exactly get the commands to work with grbl plotter, not sure if you have any experience with that, I'm still waiting for a reply from Sven.

**Comment by fra589** [comment]
Hi @jbaker1311,  
  
Is M62-M65 commands are working with a terminal (you can use [Putty](https://www.putty.org/) with serial connection at 115200 bps) or another GCode sender?  
Can you post the $I output to see which exact version of grbl-Mega-5X you have?  
  
@++;  
Gauthier.

**Comment by jbaker1311** [comment]
Thanks for the reply, I've dumped the idea of using the digital outputs for now. As I can use flood and coolant to switch my relays. I haven't tried any other software as I'm only using my machine for a plotter/cutter and not a CNC/foam cutter. I can get back to you tomorrow with grbl version. Cheers

**Comment by fra589** [comment]
No news from near a month... Issue closed.
