### ISSUE TITLE
Cloned X and Y Axis: Normal movement fine but only one motor runs during homing

### ISSUE THREAD

**Issue by beyertom** [fra589/grbl-Mega-5X#309]
Hi all,

i wasted now several hours debugging my problem. I build a MPCNC Primo with a RAMPS Board with the newest grbl-Mega-5X Firmware. As the subject says, the Movement of the Axis is fine but when i execute $H only the cloned X motor is running. I tried to change order of homing so Y is homed first. Then only cloned Y motor is running.

All Endstops on X and Y are in "min" position. No Endstop on Z.

Output of ? when no endstop is triggered:
`<Alarm|MPos:35.010,0.000,10.000,35.010,0.000|FS:0,0>`

Output when for example cloned Y is triggerd:
`<Alarm|MPos:35.010,0.000,10.000,35.010,0.000|FS:0,0|Pn:Y>`

The triggering for all 4 Endstops work fine.

Please find here my $$:
```
$0 = 10    (Step pulse time, microseconds)
$1 = 254    (Step idle delay, milliseconds)
$2 = 0    (Step pulse invert, mask)
$3 = 0    (Step direction invert, mask)
$4 = 0    (Invert step enable pin, boolean)
$5 = 0    (Invert limit pins, boolean)
$6 = 0    (Invert probe pin, boolean)
$10 = 1    (Status report options, mask)
$11 = 0.020    (Junction deviation, millimeters)
$12 = 0.002    (Arc tolerance, millimeters)
$13 = 0    (Report in inches, boolean)
$20 = 0    (Soft limits enable, boolean)
$21 = 1    (Hard limits enable, boolean)
$22 = 1    (Homing cycle enable, boolean)
$23 = 27    (Homing direction invert, mask)
$24 = 25.000    (Homing locate feed rate, mm/min)
$25 = 250.000    (Homing search seek rate, mm/min)
$26 = 250    (Homing switch debounce delay, milliseconds)
$27 = 5.000    (Homing switch pull-off distance, millimeters)
$30 = 20000    (Maximum spindle speed, RPM)
$31 = 550    (Minimum spindle speed, RPM)
$32 = 0    (Laser-mode enable, boolean)
$100 = 200.000    (X-axis travel resolution, step/mm)
$101 = 200.000    (Y-axis travel resolution, step/mm)
$102 = 4000.000    (Z-axis travel resolution, step/mm)
$103 = 200.000   
$104 = 200.000   
$110 = 3000.000    (X-axis maximum rate, mm/min)
$111 = 3000.000    (Y-axis maximum rate, mm/min)
$112 = 150.000    (Z-axis maximum rate, mm/min)
$113 = 3000.000   
$114 = 3000.000   
$120 = 170.000    (X-axis acceleration, mm/sec^2)
$121 = 170.000    (Y-axis acceleration, mm/sec^2)
$122 = 170.000    (Z-axis acceleration, mm/sec^2)
$123 = 170.000   
$124 = 170.000   
$130 = 760.000    (X-axis maximum travel, millimeters)
$131 = 560.000    (Y-axis maximum travel, millimeters)
$132 = 130.000    (Z-axis maximum travel, millimeters)
$133 = 760.000   
$134 = 560.000   
```

Here the relevant area of the config.h:
```
#define N_AXIS 5        // Number of axes (3 to 6)
#define N_AXIS_LINEAR 5 // Number of linears axis, must be <= N_AXIS

// Axis indexing and names
#define AXIS_1 0        // Axis indexing value. Must start with 0 and be continuous.
#define AXIS_1_NAME 'X' // Axis names must be in X, Y, Z, A, B, C, U, V, W, D, E & H.
#define AXIS_2 1
#define AXIS_2_NAME 'Y'
#define AXIS_3 2
#define AXIS_3_NAME 'Z'
#if N_AXIS <3
  #error "N_AXIS must be >= 3. N_AXIS < 3 is not implemented."
#endif
#if N_AXIS > 3
  #define AXIS_4 3
  #define AXIS_4_NAME 'X' // Letter of axis number 4
#endif
#if N_AXIS > 4
  #define AXIS_5 4
  #define AXIS_5_NAME 'Y' // Letter of axis number 5
#endif
#if N_AXIS > 5
  #define AXIS_6 5
  #define AXIS_6_NAME 'C' // Letter of axis number 6
#endif
#if N_AXIS > 6
  #error "N_AXIS must be <= 6. N_AXIS > 6 is not implemented."
#endif
```

```
#if N_AXIS == 4 // 4 axis : homing
  #define HOMING_CYCLE_0 (1<<AXIS_3) // Home Z axis first to clear workspace.
  #define HOMING_CYCLE_1 ((1<<AXIS_1)|(1<<AXIS_2))     // OPTIONAL: uncomment to move X,Y at the same time.
  //#define HOMING_CYCLE_1 (1<<AXIS_1) // Home X axis  // OPTIONAL: uncomment to move only X at a time.
  //#define HOMING_CYCLE_2 (1<<AXIS_2) // Home Y axis  // OPTIONAL: uncomment to move only Y at a time.
  //#define HOMING_CYCLE_3 (1<<AXIS_4) // Home 4th axis (A)
#elif N_AXIS == 5 // 5 axis : homing
    #define HOMING_CYCLE_0 ((1<<AXIS_1)|(1<<AXIS_4)) // Home X axis
    #define HOMING_CYCLE_1 ((1<<AXIS_2)|(1<<AXIS_5)) // Home Y axis
#elif N_AXIS == 6 // 6 axis : homing
  #define HOMING_CYCLE_0 (1<<AXIS_3) // Home Z axis first to clear workspace.
  #define HOMING_CYCLE_1 ((1<<AXIS_1)|(1<<AXIS_2))     // OPTIONAL: uncomment to move X,Y at the same time.
  //#define HOMING_CYCLE_1 (1<<AXIS_1) // Home X axis  // OPTIONAL: uncomment to move only X at a time.
  //#define HOMING_CYCLE_2 (1<<AXIS_2) // Home Y axis  // OPTIONAL: uncomment to move only Y at a time.
  //#define HOMING_CYCLE_3 (1<<AXIS_4) // Home 4th axis (A)
  //#define HOMING_CYCLE_4 (1<<AXIS_5) // Home 5th axis (B)
  //#define HOMING_CYCLE_5 (1<<AXIS_6) // Home 6th axis (C)
#else // Classic 3 axis
  #define HOMING_CYCLE_0 (1<<AXIS_3) // Home Z axis first to clear workspace.
  #define HOMING_CYCLE_1 ((1<<AXIS_1)|(1<<AXIS_2))     // OPTIONAL: uncomment to move X,Y at the same time.
  //#define HOMING_CYCLE_1 (1<<AXIS_1) // Home X axis  // OPTIONAL: uncomment to move only X at a time.
  //#define HOMING_CYCLE_2 (1<<AXIS_2) // Home Y axis  // OPTIONAL: uncomment to move only Y at a time.
#endif
```

Thank you so much for your support!

**Comment by fra589** [comment]
Hi @beyertom,  
  
Your configuration (config.h and $$) seams fine to me and should be working...  
  
Perhaps there is another problem.  
Have you tested this configuration the first time you have uploaded Grbl on your card? 
If not, did you delete the old version of Grbl in the library directory as indicated in the wiki (https://github.com/fra589/grbl-Mega-5X/wiki/Compiling-grbl-Mega-5X) ?  
![image](https://user-images.githubusercontent.com/19529154/209297699-e84e4e02-4944-4042-a708-c52c3eea8d6a.png)
Finally, did you run the Grbl command "$RST=*" to reset the flash after the axis configuration change?  
  
Can you tell me if you are using Linux or Windows to compile and flash Grbl to your board?  
Can you post the result of the $I command so that I have as much detail as possible to understand your problem?  
  
@++;  
Gauthier.

**Comment by fra589** [comment]
No follow-up on this problem for 2 weeks... :disappointed: => Closed issue!
I take the time to answer this type of question, a feedback on the answer would be appreciated...  
  
@++;  
Gauthier.

**Comment by beyertom** [comment]
I am sorry for my late response and thanks for reminding me to reply to the issue and giving me very helpfull hints.

After reading your comment i did following things:

1. I never did a `make clean` when i flashed my device
2. I (think) i never did a `$RST=*`
3. Iam running Arch Linux, but what i dont get from the guide is about deleting the library (i dont even have arduino installed).

None resolved the problem.

Today i had more time to tinker with the machine, and iam coming to the conclusion the its a wiring problem with the X1 and Y1 endswitches.

If i assign these switches to X2 and Y2 motors, then these motors show the wrong behavior.

I will do more analysis (and hopefully fixes) during the next week and will report back.

**Comment by fra589** [comment]
Hi @beyertom,  
Thanks for the feedback.
I reopen this issue waiting for your next report.

@++;
Gauthier.

**Comment by beyertom** [comment]
Hi @fra589 ,

it was indeed a wiring issue. I accidentally switched GND with the SHIELD cable in the plugs of the Endstops of X1 and Y1.

During Homing the Endstops got immediately triggerd and stopped X1 and Y1 from moving.

Why it worked during normal operation, no idea....

Nevertheless: I fixed my wiring problem and everything is working perfectly.

Thank you very much for your support!

**Comment by RaphaelDives** [comment]
> Hi @fra589 ,
> 
> it was indeed a wiring issue. I accidentally switched GND with the SHIELD cable in the plugs of the Endstops of X1 and Y1.
> 
> During Homing the Endstops got immediately triggerd and stopped X1 and Y1 from moving.
> 
> Why it worked during normal operation, no idea....
> 
> Nevertheless: I fixed my wiring problem and everything is working perfectly.
> 
> Thank you very much for your support!

…because in normal operation (without using hard limits - which is standard config) the endstops are ignored… 😉
Good that it’s working now!
Another functional grbl-mega-5x cnc! 😎
