### ISSUE TITLE
renaming axis from software

### ISSUE THREAD

**Issue by ariefadha** [fra589/grbl-Mega-5X#314]
hi, I'm using 4 independent axis foam cutter with rotary axis so it only can run G01, not G02 or G03, because arc movement cannot translate to UV axis.

however sometimes I want to use this 4 axis machine to cut foam like 2 axis or 2 axis + rotary axis. And the gcode use Arc movement. In mean time I have to unplug the UV axis and put parallel to XY axis driver motor (acting as duplicate stepper), so it can move and accept arc gcode.

So if I can rename UV axis from software so it can move same like XY, I dont need to unplug-plug the stepper wire for paralleling UV to XY.

**Comment by fra589** [comment]
Hi @ariefadha,  
  
I'm afraid it's not possible to have a dynamic rename functionality.  
Axis names are defined at compilation time by constants and not by variables. Unless rewriting a very large part of the code and have a risk of losing a lot of optimization, it's not possible to change axes names after compilation.  
  
@++;  
Gauthier.
