### ISSUE TITLE
3018 cutter comp

### ISSUE THREAD

**Issue by mg-jones-uk** [fra589/grbl-Mega-5X#317]
Hi i have a 3018 but can not seem to input cutter comp, it doesnt recognize G41 G42 or where to put in cutter dia, help

**Comment by fra589** [comment]
Hi @mg-jones-uk,  
  
Cutter radius compensation (G41 / G42) is not supported by Grbl.
Cutter radius is generally defined by the FAO software.

@++;
Gauthier.

**Comment by mg-jones-uk** [comment]
Thankyou for the reply, I had my suspicions   
  
  
  
  
  
  
  

  
  
>
