### ISSUE TITLE
question: will work for 3d printer?

### ISSUE THREAD

**Issue by ariefadha** [fra589/grbl-Mega-5X#319]
I want to use my cnc as 3d printer too by changing the spindle with hot-end. So can grbl mega 5x work for 3d printer machine configuration and 3d printer software?

**Comment by fra589** [comment]
Hi @ariefadha,  

Many 3D printer firmware are derived from the original grbl, but with great changes and evolutions.
grbl-Mega-5X is not designed to animate 3D printers. It might be possible with some modifications to divert an axis to drive the extruder, but it would be necessary to ensure several functionalities that Grbl lacks to perform all the functions of a 3D printer (management of the temperatures of the hot-end and the heated bed , bed leveling, end of filament detection, etc.).
This is another craft that other open source firmware does very well.

@++;  
Gauthier.
