### ISSUE TITLE
Spindle PWM signal not working in Arduino Mega 2560 and ramps 1.4.

### ISSUE THREAD

**Issue by Girishking** [fra589/grbl-Mega-5X#322]
Hello, how to use spindle-PWM signal in Ramps 1.4 and Arduino mega ?
i want to use Servomotor in spindle-PWM signal pins,   now iam using  " grbl mega 5X" firmware, 
I’ve been through the config.h spindle settings and checked cpu_map.h but nothing fixes this issue.

**Comment by fra589** [comment]
Hi @Girishking,  
  
@svenhb opened identical issue than this one.
Reply given here: https://github.com/fra589/grbl-Mega-5X/issues/323#issuecomment-1486417470  
  
I close this one as duplicate as I already replied to Swen.  
  
@++;  
Gauthier.  
P.S. I specify all the same that the spindle PWM signal works correctly, it is unfortunately not compatible for the use of a servomotor.
