### ISSUE TITLE
GRBL Windows 10 Configuration Tool now supports grbl-Mega-5X

### ISSUE THREAD

**Issue by PulseTrainHat** [fra589/grbl-Mega-5X#33]
Thanks for all the work on  grbl-Mega-5X.

Thought this may be of interest to some people that want to use a GUI to setup the parameters.

https://www.microsoft.com/en-gb/p/grbl-windows-10-configuration-tool/9n4b6wr9v1p0?activetab=pivot:overviewtab

Cheers

Sean

**Comment by fra589** [comment]
Hi,
Thanks for this info, may be helpful.
Parameters setup GUI also available in [cn5X](https://github.com/fra589/cn5X) :  
![Capture d’écran_2019-04-12_08-54-31](https://user-images.githubusercontent.com/19529154/56017835-b768e980-5d00-11e9-8ced-ba9230c837c2.png)
@++;
Gauthier.
