### ISSUE TITLE
Voltage requirement: Limit Switch

### ISSUE THREAD

**Issue by milesmiles902** [fra589/grbl-Mega-5X#337]
The limit (or homing) control sequence does not respond. 

When optically blocked, each switch (except for the replacement order) outputs 1 volt.

From my best understanding, `#define DISABLE_LIMIT_PIN_PULL_UP` should be enabled for Arduino to receive an input signal on (e.g. D2/D3),

Although, as there is no response, alarm, debounce, or pull-off. 

During `$H`, I sent a manual signal into the Arduino between 7-12 V, and still nothing occurred.

Here are my settings:
```
$0=10
$1=254
$2=0
$3=1
$4=0
$5=1
$6=0
$10=1
$11=0.020
$12=0.002
$13=0
$20=1
$21=1
$22=1
$23=1
$24=10.000
$25=20.000
$26=250
$27=20.000
$30=12000
$31=550
$32=0
$100=128.000
$101=142.000
$102=71.000
$103=250.000
$104=400.000
$110=100.000
$111=100.000
$112=300.000
$113=300.000
$114=10.000
$120=10.000
$121=10.000
$122=20.000
$123=5.000
$124=50.000
$130=300.000
$131=300.000
$132=200.000
$133=360.000
$134=180.000
```

Am I using the wrong pin? Is there another setting?

**Comment by fra589** [comment]
Hi @milesmiles902, 

Your understanding of `#define DISABLE_<*>_PIN_PULL_UP` is right.

From the datasheet (DC Characteristics):
- The lowest value where the pin is guaranteed to be read as high is 0.6 x VCC when VCC is in the range 2.4V to 5.5V.
- The maximum voltage is VCC + 0.5V.

**So, if you use a 5V power, the minimum voltage requirement is 3V and the maximum is 5.5V!**

- Sending 1V is clearly not enough,
- Sending 7-12V signal may destroy the pin...

Pins used for limits are described in the wiki: https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout

**WARNING**: When the pull-ups are disabled, this requires additional wiring with pull-down resistors to limit current!

@++;
Gauthier.

**Comment by milesmiles902** [comment]
Agreed.
