### ISSUE TITLE
Open-source?

### ISSUE THREAD

**Issue by mileticveljko** [fra589/grbl-Mega-5X#345]
How is grbl-Mega-5X open-source project, when you hide your source with gitignore?

**Comment by fra589** [comment]
Hello @mileticveljko,  
  
The .gitignore files are used only to avoid polluting the repository with elements that have nothing to do with the grbl-Mega-5X sources.

.main gitignore:
```
*.hex
*.zip
*.o
*.elf
*.d
```
=> compilation results: are not part of the grbl-Mega-5X sources.
```
.grbl*
```
=> GCode files for tests: are not part of the grbl-Mega-5X sources (there is none for this moment).
```
*.DS_Store
.vscode
platformio.ini
```
=> Microsoft IDE editor configuration files. I don't use Visual Studio Code or PlatformIO, these files polluted my system during a Pull Request from elsewhere. 
I develop and maintain grbl-Mega-5X under Linux Debian with a simple text editor (Geany or vi) and compile it with a Makefile and avr-gcc.

```
README.md
```
=> presentation of grbl-Mega-5X for the github.com site: is not part of the grbl-Mega-5X sources and is updated directly online.

build/.gitignore:
```
# Ignore everything in this directory
*
# Except this file
!.gitignore
```
=> build is the temporary building directory defined in the Makefile, it's not part of grbl-Mega-5X sources and only hosts temporary files.


**There are no hidden source files, all sources files of grbl-Mega-5X are hosted and apparent in this repository.**

grbl-Mega-5X is open source under the GNU GENERAL PUBLIC LICENSE Version 3:
https://github.com/fra589/grbl-Mega-5X/blob/edge/COPYING

@++;
Gauthier.
