### ISSUE TITLE
is frequently change $ value will worn out EEPROM?

### ISSUE THREAD

**Issue by ariefadha** [fra589/grbl-Mega-5X#348]
for example if my machine has laser and spindle. is changing between "laser mode" will worn out the atmega EEPROM in long run?

**Comment by svenhb** [comment]
More than 100000 cycles...
Here is a discussion about: https://arduino.stackexchange.com/questions/226/what-is-the-real-lifetime-of-eeprom#:~:text=ATMEL%20says%20the%20cell%20lifetime,about%20100%2C000%20write%20cycle%2F%20cell.

**Comment by ariefadha** [comment]
> More than 100000 cycles... Here is a discussion about: https://arduino.stackexchange.com/questions/226/what-is-the-real-lifetime-of-eeprom#:~:text=ATMEL%20says%20the%20cell%20lifetime,about%20100%2C000%20write%20cycle%2F%20cell.

yeah I know that, ever wonder why shutter in DSLR camera worn out? its because eeprom. for hobbies might need hundred of years to reach that. but for semi manufacturing machine it can reach 3-5 years.

but replacing atmega is easy task for me tho. just have some OCD asking this.
