### ISSUE TITLE
soft  limit issue

### ISSUE THREAD

**Issue by hzxiaoyu** [fra589/grbl-Mega-5X#35]
Hi! I set limits for each axis, XY is - dir, Z is +dir, now  homing is right, hard limit not work I know is bug
But with soft limit ,axis also can't move "An error was detected while sending"j=g21g91z1f800",error:15.
The machine position shows "x-249,y-149,z-1" after homing.
So what's wrong?

**Comment by walterwissmann** [comment]
hi hzxloyu,

you should find an answer in config.h line 126 to 196.

BR
Walter
