### ISSUE TITLE
Compatibilidad Mega + GRBL

### ISSUE THREAD

**Issue by IgnacioZeus** [fra589/grbl-Mega-5X#363]
I have my Prusa 3D printer with an Arduino Mega and a RAMPS 1.4. I just bought a laser from China and I would like to use my hardware setup to switch between printer and laser cutter. The hardware is already assembled and ready to use, but I can't find a firmware and laser cutting software version that communicate well. Some versions of GRBL turn on the laser but don't move, and some versions of Marlin move but don't turn on the laser. I've been going crazy for 3 days now. I've already activated mode $32=1 to activate laser mode, and also uncommented the laser feature in Marlin, but nothing works. If you could be so kind as to provide me with a firmware for Arduino Mega that I can burn with the IDE or with a HEX file, and a slicer or laser software that are compatible with each other, I would appreciate it, or any configuration that I missed.

Thank you.

**Comment by fra589** [comment]
HI @IgnacioZeus,  
  
grbl-Mega-5X is specially written for Arduino Mega and RAMPS 1.4.
The laser driving is a standard functionality of it.
You can use LaserGRBL (https://github.com/arkypita/LaserGRBL / http://lasergrbl.com) to drive grbl-Mega-5X from a Windows computer.

You can find many information for configuring grbl-Mega-5X in it's wiki: https://github.com/fra589/grbl-Mega-5X/wiki

The main goal of Grbl is for CNC milling and laser cutting, but not for 3D printing...
If you want to switch between printing and laser cutting, you will need to change and flash the firmware each time you will want to switch : Marlin for printing and Grbl for laser.
This may damage your board in a short time...

@++;
Gauthier.
