### ISSUE TITLE
gestion changeur outil 

### ISSUE THREAD

**Issue by supernono-fr** [fra589/grbl-Mega-5X#372]
bonjour Gauthier

je souhaiterais savoir si le gcode M6 est implémenter dans GRBL 5x ?
a première vue il me semble que non, est il possible de l'implémenter ?

je voudrais ajouter un changeur d'outil et un collecteur de copeaux motorisé A ma machine comme on peut le voir dans cette video : 

[https://youtu.be/ZeOUdosoEBM?t=1763](url) 

la configuration de la machine serait donc X Y1 Z W Y2 
Y2 est en dernière position car c'est la seule méthode fonctionnelle que j'ai trouvé pour masquer son affichage dans CNCJS !!!

cordialement
arnaud

hello Gauthier

I would like to know if the gcode M6 is implemented in GRBL 5x?
At first glance it seems to me that no, is it possible to implement it?

I would like to add a tool changer and a motorized chip collector to my machine as shown in this video: 

[https://youtu.be/ZeOUdosoEBM?t=1763](url) 

the machine configuration would therefore be X Y1 Z W Y2 
Y2 is in last position because it is the only functional method I found to hide its display in CNCJS!!

cordially
arnaud

**Comment by fra589** [comment]
Bonjour Arnaud,

Effectivement, M6 n'est pas implémenté, je n'ai pas prévu de le faire. Je pense que ça serait trop complexe.

Le mot clé T est implémenté pour mémorisation du n° d'outil et renvoi de ce numéro dans le status.

Dans le cas d'un changement manuel, je considère que c'est plutôt au logiciel d'interface de trapper les changements d'outil M6, d'afficher un message et de faire une pause en attendant le retour de l'utilisateur.
Dans le cas d'un changeur d'outil, il en existe de trop nombreux pour pouvoir les coder tous, c'est donc la encore au logiciel d'interface de trapper les changements d'outil M6 et d'envoyer l'ordre de changement au changeur d'outil.

En tout état de cause, c'est tout a fait possible d'ajouter dans gcode.c, la reconnaissance du code M6
`case 'M':` à la ligne 260
Puis, ajouter `case 6:` et traitement après la ligne 280...

Malheureusement pour toi, je trouve que c'est trop spécifique pour que je l'implémente, et de plus, je n'ai vraiment pas le temps de le faire.

Si tu essaies de t'y attaquer, je pourrais te répondre si tu as des question spécifiques.

@++;
Gauthier.
