### ISSUE TITLE
Soft limits will not allow A Axis movement in any positive direction

### ISSUE THREAD

**Issue by CNCWoodworker** [fra589/grbl-Mega-5X#374]
Bon Jour Gauthier #fra589: 

How are you? In my machine I need some verification that limits are not exceeded for machine safety, so I'm almost ready setting up my machine to work with soft limits as you recommended. As you mentioned, enabling hard limit verification while operating does affect performance. 
When I enable the soft limits, my A axis is only allowed to move in a negative direction. if the A starts at a negative value it does allow movement in a positive direction until it gets back to zero, but not past zero to positive; this behaviour seems correct for linear axis, but I think that for a rotary unlimited moving axis this is incorrect. 
Is there a setting I should use? or any recommendation?

**Comment by fra589** [comment]
Hi @CNCWoodworker,
  
Sorry for the late reply, I'm traveling very far from home.
For your unlimited A rotational axis, you can use 0 (zero) as axis maximum travel, this will disable the soft limit for this axis. So, it will be unlimited as you need.
See https://github.com/fra589/grbl-Mega-5X/wiki/Grbl-Configuration#130-131-132-133-134-135--xyzabc-max-travel-mm-degree

@++;
Gauthier.

**Comment by CNCWoodworker** [comment]
Merci Beaucoup!Bon VoyageEZSent from my iPhoneOn Jul 24, 2024, at 2:35 AM, Gauthier Brière ***@***.***> wrote:﻿
Hi @CNCWoodworker,
Sorry for the late reply, I'm traveling very far from home.
For your unlimited A rotational axis, you can use 0 (zero) as axis maximum travel, this will disable the soft limit for this axis. So, it will be unlimited as you need.
See https://github.com/fra589/grbl-Mega-5X/wiki/Grbl-Configuration#130-131-132-133-134-135--xyzabc-max-travel-mm-degree
@++;
Gauthier.
