### ISSUE TITLE
mega 2560 5x  Stepper motor does not move

### ISSUE THREAD

**Issue by parkgeonhun** [fra589/grbl-Mega-5X#375]
When you enter the program, you can hear the sound of the stepper motor running, but the motor actually vibrates and does not move. And the a and b axes do not work. It also says that there is an error in the Arduino code.
![스크린샷 2024-07-27 223506](https://github.com/user-attachments/assets/1e92910d-f5a6-415e-b4dc-42bdb1b36975)
![스크린샷 2024-07-27 223759](https://github.com/user-attachments/assets/c05d7607-d248-467d-a2aa-23369d1f66f5)

**Comment by fra589** [comment]
Hi @parkgeonhun,

> the stepper motor running, but the motor actually vibrates and does not move.

Probably an Hardware and/or config problem
- too load on the motor,
- speed or acceleration or both too high,
- ...

What is your config ? 
- `$I` and `$$` results,
- Any change in config.h, default.h & cpu_map.h ?

> there is an error in the Arduino code

Do you read and respect the procedure : https://github.com/fra589/grbl-Mega-5X/wiki/Compiling-grbl-Mega-5X ?

@++;
Gauthier.

**Comment by parkgeonhun** [comment]
What version of Arduino version does it use? If it's the latest version, I need a zip file. I just can't upload the file.

**Comment by parkgeonhun** [comment]
What version of Arduino version does it use? If it's the latest version, I need a zip file. I just can't upload the file.

**Comment by parkgeonhun** [comment]
Also, how do I resolve this error?
![Uploading 스크린샷 2024-07-30 002721.png…]()
