### ISSUE TITLE
How do I resolve this error? A axis and B axis do not work

### ISSUE THREAD

**Issue by parkgeonhun** [fra589/grbl-Mega-5X#376]
How do I resolve this error? A axis and B axis do not work
![스크린샷 2024-07-30 111952](https://github.com/user-attachments/assets/d3089092-a634-43a0-b8d9-e72998b3e120)

**Comment by fra589** [comment]
HELLO @parkgeonhun,  
  
You have a library conflict with another Grbl install in your library directory.
Remove all precedents grbl (either other grbs that are not grbl-Mega-5X) from your library directory.

From [wiki](https://github.com/fra589/grbl-Mega-5X/wiki/Compiling-grbl-Mega-5X) :
![image](https://github.com/user-attachments/assets/30e3e440-f1cb-41f3-8f00-6a82ad1b13f7)

Read carefully the wiki: https://github.com/fra589/grbl-Mega-5X/wiki/Compiling-grbl-Mega-5X then strictelly apply it.

Compiling on Arduino version 1.X: https://www.youtube.com/watch?v=-6MWMOZ5Qz4
On Arduino 2.X: https://www.youtube.com/watch?v=eFWJ6sa7IUk

@++;
Gauthier.
