### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by parkgeonhun** [fra589/grbl-Mega-5X#377]
I've tried all the methods you've told me, but the error doesn't go away. I really want to solve this problem, so I want to build a 5-axis machine. Can you send me a Mega 2560 board that works well as a courier?
![스크린샷 2024-07-30 111952](https://github.com/user-attachments/assets/df8e13f4-9773-45d2-9cc8-c09c3acead7b)

**Comment by fra589** [comment]
Duplicate issue of #376... issue #376 closed!

Please, don't open new issue when you are not able to understand and apply the answer to the previous issue.

Compiling grbl-Mega-5X works fine with Arduino IDE 1.8.19.
**https://github.com/fra589/grbl-Mega-5X/wiki/Compiling-grbl-Mega-5X**

You must be pretty much the only one who can't do it!
Start over with a fresh install of the Arduino IDE after deleting all its files and settings and it should work!

@++;
Gauthier.
