### ISSUE TITLE
6-Axis Prototype Breakout Board

### ISSUE THREAD

**Issue by PulseTrainHat** [fra589/grbl-Mega-5X#38]
Just received the PCB back for first prototype 6-Axis Breakout Board.

Have gone for Open Collector Buffers on each output and Opto Isolated inputs for each Limit input.

![6-axis-Protoype PCB](https://user-images.githubusercontent.com/29014510/54355845-0d8b3400-4652-11e9-94db-30c05974a855.jpg)

This is based on Ramps 1.4 configuration for pin out.

Also there are headers for a calibration PCB to be connected to the breakout board.
This calibration circuit is for any Axis that has two motors on it and will home each individually which will line them up correctly. 

Now to find time to solder up and test :)

Cheers

Sean

**Comment by RaphaelDives** [comment]
Hey there, looks great! But all the work soldering SMD's…. Have fun! 😎

**Comment by PulseTrainHat** [comment]
We have solder stencil for it and also Re-Flow oven, so not too bad a job hehe :)

**Comment by raenji-sk** [comment]
Hello Sean, any update on price / availability?
Will it support inductive endstops as your GRBL Breakout/Shield for Arduino Uno CNC Controller Kit?
BTW that one works great, but I could use the auto squaring feature for the Y axis.

Andrej
