### ISSUE TITLE
Mega Ramps 1.4 CNC XYZ motors do not move

### ISSUE THREAD

**Issue by walterbux** [fra589/grbl-Mega-5X#39]
Hello,
I have built a 5 axes CNC XYZBC with Mega and RAMPS 1.4. Works perfectly with 4 of 5 axes with Repetier FW. No motion of XYZ motors with grbl-Mega-5X. Tested with GrblPanel apparently shows no error in the dialogue but no motion. The motors are Nema 23 with DQ542MA drivers.
Any advice ?
Thanks for the very interesting work and project.

Walter

**Comment by fra589** [comment]
Hi Walter,  
Have you make a complete factory reset ($RST=*) after changing the firmware ?  
Is it possible than some Repetier FW params are stored in the eeprom and are incompatible with Grbl...  
Grbl does not reset the eeprom by itself.   
@++;  
Gauthier.

**Comment by walterbux** [comment]
Hi Gauthier,
happy to hear from you !
No, I have not made any reset.
I retry and give you an answer..
See you soon.

Walter

**Comment by walterbux** [comment]
Hi Gauthier,
I have sent the reset. Same behaviour, no motion of x, y, z axes.
No error in the dialogue.

Walter

**Comment by walterbux** [comment]
When I connect the usb port I hear the noise that make motors when energized: a little shot but after no motion. As a note I have made a standard connection of the drivers: I attach the schematic. I have not the second Y motor. The extruders are not connected.
Walter
![Electronics](https://user-images.githubusercontent.com/8451091/55318878-0d719d80-5474-11e9-904d-b95bad4e2bd8.jpg)

**Comment by fra589** [comment]
Hi Walter,
Since the signals (step pulse) are +5v impulses, I think you have wrongs wiring for your drivers.
The good wiring should be this :  
![RampstoDriverWiring](https://user-images.githubusercontent.com/19529154/55342213-930f4080-54a8-11e9-9c52-7cec2bd2cbc0.png)
@++;  
Gauthier.

**Comment by walterbux** [comment]
Wow !! may be you are right !! But I have just reviewed the repetier fw settings and I have selected
Invert direction (INVERT_X_DIR)
Invert enable signal (X_ENABLE_ON)
and everything is working perfectly.
May I have a chance to leave the hw like it is making sw modifications in grbl ?
Do you have advices on the matter because to change the HW is really bloody.
Thanks in advance, you are very kind.

Walter

**Comment by walterbux** [comment]
The driver I/F allows my wiring..
Walter

![IFdriver](https://user-images.githubusercontent.com/8451091/55355376-65d28a80-54c8-11e9-873c-131d0378900c.jpg)

**Comment by walterbux** [comment]
And even your advised wiring.

Walter

![IFdriver2](https://user-images.githubusercontent.com/8451091/55363443-5ad62500-54dd-11e9-889d-2f3efa7f16f8.jpg)

**Comment by walterbux** [comment]
Hello Gauthier,
problem solved with the commands:
$2=7
$3=7
$4=1

Now the motors XYZ are working ...
:) 👍

**Comment by fra589** [comment]
Cool ! Issue closed :smiley:
