### ISSUE TITLE
Communication errorr using cn5X

### ISSUE THREAD

**Issue by walterbux** [fra589/grbl-Mega-5X#41]
Hello Gauthier,
I receive this error message when connecting to the MEGA.
If I try another sender like GrblPanel I have no error while connecting.
What to do ? May I change some interface setup in cn5X ?

![Errore_sender](https://user-images.githubusercontent.com/8451091/55396225-ae7b5980-5543-11e9-89ce-1f36106ce0ae.jpg)

**Comment by walterbux** [comment]
In debug mode I have ...

![Debug](https://user-images.githubusercontent.com/8451091/55397198-fa2f0280-5545-11e9-8bc4-d0863ccc7388.jpg)

**Comment by fra589** [comment]
Hi @walterbux,  
At first look, it seems you use a Windows version that is not the up to date development one...  
Can you post the "About cn5X" screenshot please ?
@++;
Gauthier.

**Comment by walterbux** [comment]
Here it is..
Moreover I see the same behaviour described in cn5X issue 1:
https://github.com/fra589/cn5X/issues/11
"...starting first the serial monitor of arduino ide then its software instead the whole connects and works without any error...".

Walter


![SW-Version](https://user-images.githubusercontent.com/8451091/55473096-10a09100-560e-11e9-8149-54a4e8684dae.jpg)

**Comment by walterwissmann** [comment]
Hi Walter,
I think, that is an 'Earth Issue' ;)

But it cut be that is an issue about the USB from the arduino...
Please give us a near clear picture of your arduino board, Walter.

BR
Walter <- ( Namebrother ) :)

**Comment by walterbux** [comment]
I don't have a picture: I connect my laptop battery powered to a mega + ramps board with only the usb cable. no other power than that usb provided and the issue is there.
But, if I open Arduino correctly configured to flash grbl to Mega with the correct port number and I open the serial monitor, I see the grbl answer. I close the Arduino IDE. I open cn5X and everything is ok. no error.
If I power on the pc and simply open cn5X and connect the error appears.
My os is the last version of Windows 10.
I have installed Python 3.7 64 bits.

Thank you again for your work.

Walter

**Comment by walterwissmann** [comment]
Ahh, ok.

Could you please install this little serial terminal program and test it with the same procedure?
https://github.com/pyserial/pyserial/blob/master/serial/tools/miniterm.py

**Comment by fra589** [comment]
> @walterbux wrote :  
> But, if I open Arduino correctly configured to flash grbl to Mega with the correct port number and I open the serial monitor, I see the grbl answer. I close the Arduino IDE. I open cn5X and everything is ok. no error.
> If I power on the pc and simply open cn5X and connect the error appears.
> My os is the last version of Windows 10.
> I have installed Python 3.7 64 bits.
> (...)

Ho, interesting behavior !  
I'll be able to test this tonight, and perhaps understand this issue soon...

By the way, the latest version is 0.3.g, but changes since 0.3.f don't affect initial connection sequence. Therefore, the bug must always be present.

@++;  
Gauthier.

**Comment by walterbux** [comment]
Both before and after pc restart no error or anomaly...

Walter

![OK before pc restart](https://user-images.githubusercontent.com/8451091/55482776-89f7ae00-5625-11e9-8e9f-f410f9ae13aa.jpg)
![OK after pc restart](https://user-images.githubusercontent.com/8451091/55482789-911ebc00-5625-11e9-99d8-5076095407cd.jpg)

**Comment by walterwissmann** [comment]
Awesome :)
Now, Gauthier should have enough info to find the bug ;)

BR
Walter

**Comment by walterbux** [comment]
Yes, very good :), many thanks. but do not forget to give me the link to download the last revision of cn5X sw.

Walter

**Comment by fra589** [comment]
Hi Walter(s) ;-)  
It seem to be a cn5X specific problem on Windows...  Can't reproduce on Linux, Perhaps the code have too speed for W$ :-)  
Can you try the latest cn5X version (0.3.h) from here : https://github.com/fra589/cn5X ?  
And if the problem persist, post the new debug informations.  
@++;  
Gauthier.

**Comment by walterbux** [comment]
Hi Gauthier and Walter,
I am sorry to inform you that nothing is changed with the new version 0.3.h. The behaviour is exactly the same as before. I do not post the images because the only thing changed is the SW version.
See you soon.

Walter

**Comment by fra589** [comment]
Hi @walterbux,
But what about the new Debug outputs ? I added some new message in the grblComSerial.py...
Now, when it work fine, the new debug output is :
```
cn5X++ (v0.3.h) : Starting debug.
grblCom.startCom(self, ttyUSB0, 115200)
grblComSerial.__openComPort(self)
grblCom.on_sig_connect(self, True)
grblComSerial: comPort ttyUSB0 open, RC = True
grblComSerial : Wait for Grbl init... T = 1554390449681 ms...
grblComSerial : Wait for Grbl init... T = 1554390449957 ms, Nothing to read on serial.
grblComSerial : Wait for Grbl init... T = 1554390450232 ms, Nothing to read on serial.
grblComSerial : Wait for Grbl init... T = 1554390450508 ms, Nothing to read on serial.
grblComSerial.__openComPort() : Buffer recu : "b"\r\nGrbl 1.1i ['$' for help]\r\n[MSG:'$H'|'$X' to unlock]\r\n""
grblComSerial : Grbl init string received in 1077 ms, OK.
grblCom.on_sig_init(self, Grbl 1.1i ['$' for help])
```
I don't nees image, just copy/past the full new debug output text of cn5X connection attempt from Debug tab...

@++;
Gauthier.

**Comment by walterbux** [comment]
Here it is.
I think nothing special.

I add that in the old version I have tried to extend the timeout from 5 to 20 s. Same behaviour.

![Debug1](https://user-images.githubusercontent.com/8451091/55582620-47ff6280-5720-11e9-8df7-59cce8bfdb48.jpg)
![Debug2](https://user-images.githubusercontent.com/8451091/55582629-4cc41680-5720-11e9-8ed6-18d81b5c51ae.jpg)

**Comment by fra589** [comment]
Hi Walter,
Since I am not able to reprocuce your problem on my Windows system, I am forced to grope...
The only thing I am sure, is that on your system, Grbl don't send his initialisation string as he normaly do on mine.
In new cn5X version (0.3.i), I added a first timeout of 1500 ms. If I don't receive the Grbl init string before this first timeout, I try to send a soft reset to Grbl, which must force him to send his init string. 

Can you try this new version ?
@++;
Gauthier.

**Comment by walterbux** [comment]
Hi Gauthier,
I understand you very well, no problem.. It is strange that you can not reproduce the error on your windows system because mine has nothing special..
I don't know where is the prolem but as signalled in the previous message I have tried to extend the timeout from 5 to 20 s inside the grblComSerial.py file, see attached point, without any result. Same behaviour therefore there is some condition that prevents the opening of the port except if I open before the same port with the Arduino Ide Serial monitor.
See you soon.

Walter

![Timeout](https://user-images.githubusercontent.com/8451091/55630559-441e1f80-57b6-11e9-83a7-fc83448368e1.jpg)
. Same behaviour.

**Comment by fra589** [comment]
In any case, your debug output tel us that the serial port is normaly open. The thing that is not normal is that cn5X does'nt receive anything when connecting to Grbl. Grbl don't send it's initialisation string!  
cn5X need this output from Grbl to verify if it is realy Grbl and to known what version is it.  

When you open the port with arduino serial monitor, does it show you it's initialisation string as showed in the following picture?    

![Capture](https://user-images.githubusercontent.com/19529154/55637701-fa3d3580-57c5-11e9-9ca6-07aa917fa6e6.PNG)
  
Have you tested the cn5X version that I posted this morning with a soft reset added in the initialisation sequence ?  

@++;
Gauthier.

**Comment by walterbux** [comment]
Hi Gauthier,
I repeat every test step for completeness:
1-pc boot
2-open a cmd window as admin
3-cd where it is .. python cn5X.py
4-select the arduino port
5-open
6-the cn5X app thinks some seconds and after shows the usual error (tested with version cn5X-0.3.h, last in github) your msg this morning saying "Can you try this new version ?" had nothing attached.

AFTER I start Arduino IDE
I do nothing else but opening serial monitor configured to send "NL + CR" !!!!!!! at 115200 baud.

Immediately grbl sends its message exactly that of your picture.

AFTER I reopen your app cn5X and magically it works !!!

Try a version that sends NL + CR just after the port is opened !!

I hope to have been clear.
See you soon.

Walter

**Comment by fra589** [comment]
Ah ! You need to enter a CR+LF in serial monitor to have the first Grbl message !!! Yes, It's clear.  

But this morning, I pushed the version 0.3.i on the github repository! => 2 files are modified from 0.3.h :  cn5X_config.py and grblComSerial.py... 
This version send a Ctrl + X to the serial after opening the serial port. This should do the job like a CR+LF...
If not, you could test replacing the line number 245 of grblComSerial.py :  
`self.__sendData(REAL_TIME_SOFT_RESET)`
by this one :  
`self.__sendData("\r\n")`
@++;
Gauthier.

**Comment by walterbux** [comment]
Wow Gauthier !!!

It works !!! :) :)

Your Ctrl + X is good as CR + LF !!
Thank you !
It has a good experience to work with you !

Walter

p.s. see you on next issue :)

**Comment by walterbux** [comment]
It has been a good.. to be quick I lose the words.

Walter
