### ISSUE TITLE
Status report max . frequency to poll?

### ISSUE THREAD

**Issue by svenhb** [fra589/grbl-Mega-5X#45]
Classic grbl for Arduino Uno / Nano recommends a max. polling frequency of 10Hz (https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#interacting-with-grbls-systems).
What is the maximum polling frequency for grbl on Mega 2560?

**Comment by fra589** [comment]
Hi @svenhb,
From empiric tests, the best polling I found with grbl-Mega-5X on Mega 2560 is waiting 75 ms between to polls (~13.33 Hz).  
This is a compromise between the update and tracking dynamics of my cn5X application that does not affect the working time of grbl-Mega-5X significantly.
@++;
Gauthier.
