### ISSUE TITLE
Uno to Mega

### ISSUE THREAD

**Issue by beckmx** [fra589/grbl-Mega-5X#46]
Hello, I would like to use this fork, I just have a couple of questions, I was using the uno version and was wondering if I can just replace the uno for the mega? and are the pins in the mega compatible with the cnc shield v3 for the 4th axis? or do you have a specific axis pin layout?

**Comment by fra589** [comment]
Hi @beckmx,
From memory, the Mega's pins are not setup the same as the Uno... So I don't think the cnc shield v3 be compatible with Mega.  
grbl-Mega-5X is writed to be used with the RAPMS 1.4 shield.  
Pins mapping is defined in the cpu_map.h file and can be updated with your need.
@++;
Gauthier.
