### ISSUE TITLE
Complete connection pin

### ISSUE THREAD

**Issue by simonefailla** [fra589/grbl-Mega-5X#5]
sorry for the question, but i dint found a complete list of pin for use all axis.
i need to use only X-Y and A axis for a TGA,also no need a endswitch on A axis because i want use it as a turntable.

**Comment by fra589** [comment]
Complete pinout is here :
https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout

**Comment by simonefailla** [comment]
thx, but i wont to use my personal driver,so it's possible to connect di driver directly on arduino? i dont know what pin of ramp are related on Arduino Mega

**Comment by fra589** [comment]
Hi, Pin definition in file cpu-map.h, in section `#ifdef CPU_MAP_2560_RAMPS_BOARD // (Arduino Mega 2560) with Ramps 1.4 Board` :  
- Step bits :  
`  #define STEP_BIT_0 0  // X Step - Pin A0  `
`  #define STEP_BIT_1 6  // Y Step - Pin A6  `
`  #define STEP_BIT_2 3  // Z Step - Pin D46  `
`  #if N_AXIS > 3  `
`    #define STEP_BIT_3 4 // Axis number 4 Step - Pin D26  `
`  #endif  `
`  #if N_AXIS > 4  `
`    #define STEP_BIT_4 1 // Axis number 5 Step - Pin D36  `
`  #endif`  `
- Direction bits :  
`  #define DIRECTION_BIT_0 1 // X Dir - Pin A1  `
`  #define DIRECTION_BIT_1 7 // Y Dir - Pin A7  `
`  #define DIRECTION_BIT_2 1 // Z Dir - Pin D48  `
`  #if N_AXIS > 3  `
`    #define DIRECTION_BIT_3 6 // Axis number 4 Step - Pin D28  `
`  #endif  `
`  #if N_AXIS > 4  `
`    #define DIRECTION_BIT_4 3 // Axis number 5 Step - Pin D34  `
`  #endif`  `
- Stepper disable bit :  
`  #define STEPPER_DISABLE_BIT_0 7 // X Enable - Pin D38  `
`  #define STEPPER_DISABLE_BIT_1 2 // Y Enable - Pin A2  `
`  #define STEPPER_DISABLE_BIT_2 0 // Z Enable - Pin A8  `
`  #if N_AXIS > 3  `
`    #define STEPPER_DISABLE_BIT_3 2 // Axis number 4 Step - Pin D24  `
`  #endif  `
`  #if N_AXIS > 4  `
`    #define STEPPER_DISABLE_BIT_4 7 // Axis number 5 Step - Pin D30  `
`  #endif  `

Hope this help you...

@++;
Gauthier.
