### ISSUE TITLE
ENHANCEMENT, Can support for MPG wheel bee added to manually jog axis and set zero (g92) from controller instead of pc, And support for reading potentiometers for feed override ?

### ISSUE THREAD

**Issue by sinfocomp** [fra589/grbl-Mega-5X#53]
The idea is to :
1.- have GRBL read 1 push button on a configurable pin to select active jog axis and lite 1 of x leds (one per axis) so each press selects a difrent axis and by long press select none, then read a MPG handwheel on configurable pins and jog acording to pulses received

2.-read potentiometers on configurable analog pins to be able to set the overides, just like from PC

3.- set an extra com port on configurable pins to be used if no USB conection is detected, so secondary code sender arduino can be used to send gcode job

4.-read a pushbutton on configurable pin and set home on press (g92x0y0z0a0 etc)

**Comment by sinfocomp** [comment]
posted a bounty for $100 if someone is willing to implement this
https://www.canwork.io/jobs/public/enhancement-to-33
counter offers welcomed

**Comment by fra589** [comment]
Hi @sinfocomp,
I don't think it will be a good id to ask to Grbl firmware to do à lot of thing like this you want.
Grbl must stay as light as possible to keep all its performance.
I think the functions you want must to be assigned to a CNC control panel. 
My CNC software control panel ([cn5X](https://github.com/fra589/cn5X)) is writen to be embeded on Rasbery PI or equivalent with a touch screen and to be dedicaced to one CNC milling machine. In the future, this type of function can certainly be implemented on [cn5X](https://github.com/fra589/cn5X).
@++;
Gauthier.
P.S. by the way, the link you posted above don't work...
