### ISSUE TITLE
Clone Y - I Don't Understand #4 and #51

### ISSUE THREAD

**Issue by mdframe** [fra589/grbl-Mega-5X#59]
I am very sorry for asking this question however this is very new to me.  I am trying to understand what I change to clone the Y axis to E1?  Are any instructions available for the steps to perform?  The previous items look to solve for this however I am just lost.

Again, I apologize for asking again.

Matt

**Comment by fra589** [comment]
Hi @mdframe,  

You just need to edit the file "grbl/config.h" :  
line 53 & 54
```
#define N_AXIS 4            // Number of axes
#define N_AXIS_LINEAR 4 // Number of linears axis
```
and line 71  
`#define AXIS_4_NAME 'Y' // Letter of axis number 4`

Then, you will have what you want.

@++;
Gauthier.
