### ISSUE TITLE
It works for cnc shield Arduino UNOI 4 axes

### ISSUE THREAD

**Issue by l337quez** [fra589/grbl-Mega-5X#60]
What a good job you are doing, I congratulate you. I have a cnc shield, I want to know if I can use your software, use gnu linux

**Comment by fra589** [comment]
Thank you for your interest about my work, unfortunately for you, grbl-Mega-5X is based on grbl-Mega witch doesn't work on Arduino Uno, but only on [Arduino Mega 2560](https://store.arduino.cc/mega-2560-r3). The shield used by default on the Mega is the [RAMP 1.4 or + card](https://reprap.org/wiki/RAMPS_1.4).
@++;
Gauthier.
