### ISSUE TITLE
Clone axis

### ISSUE THREAD

**Issue by coilheaddesigns** [fra589/grbl-Mega-5X#62]
Hey

Where do I clone axis.
Need to clone Y axis

**Comment by fra589** [comment]
Hi @coilheaddesigns,  

To have a 3 axis with the Y axis cloned :  
Edit the config.h file, 
On the line 53, use :  
` #define N_AXIS 4 // Number of axes`
and on the line number 71, type :  
` #define AXIS_4_NAME 'Y' // Letter of axis number 4`
  
Then, the axis Y will be cloned on the E0 axis on RAMPS

@++;
Gauthier.

**Comment by coilheaddesigns** [comment]
OK cool

Thank you very much.

The how do I enable the other axis for my rotary setup?

**Comment by fra589** [comment]
In config.h, define the number of axis you need on line 53 (N_AXIS) (max 6 axis), then give the name of each axis you need. If you give the same name to more than one axis, this named axis will be cloned.

For example :
#define N_AXIS 5 // Number of axes
```
(...)
#define AXIS_1_NAME 'X'
(...)
#define AXIS_2_NAME 'Y'
(...)
#define AXIS_3_NAME 'Z'
(...)
#define AXIS_4_NAME 'Y'
(...)
#define AXIS_5_NAME 'A'
```
  
Then, you will have 5 reals axis with 4 logical :  X, Y cloned on axis number 2(Y) and 4(E0), Z and the rotational A.

Don't forget to mention the number of linear (reals) axis :  
`#define N_AXIS_LINEAR 4 // Number of linears axis`
  
@++;  
Gauthier.

**Comment by coilheaddesigns** [comment]
Brilliant thank you for the response will setup tonight when I get home.

**Comment by coilheaddesigns** [comment]
When I do it like that the Y motor on E0 engages but does not move

**Comment by coilheaddesigns** [comment]
When I do it like that the Y motor on E0 engages but does not move

**Comment by fra589** [comment]
First, verify parameters of your axis : step/unit, max speed and acceleration...

**Comment by coilheaddesigns** [comment]
[Config setup](https://imgur.com/a/0E12Hxh)

**Comment by coilheaddesigns** [comment]
Still only engages y no movement

**Comment by fra589** [comment]
See the wiki page of grbl configuration (when grbl is running) here :  
https://github.com/fra589/grbl-Mega-5X/wiki/Grbl-Configuration  
  
And post the output of the "$$" grbl command...
  
For your axis cloning configuration, you need to have the same parameters for :  
- $101 (Y steps/mm) and $103 (step/unit of cloned axis)
- $111 (Y Max rate, mm/min) and $113
- $121 (Y Acceleration, mm/sec^2) and $123
- $131 (Y Max travel, mm) and $133
  
@++;
Gauthier.

**Comment by coilheaddesigns** [comment]
Got it running

**Comment by coilheaddesigns** [comment]
Homing cloned axis not homing

**Comment by coilheaddesigns** [comment]
The cloned axis moves in the Same direction with jog but on homing it does not move

**Comment by coilheaddesigns** [comment]
I have confirmed all cloned axis $values have been replicated

**Comment by fra589** [comment]
Please, take a look at previous issues and their replies before asking...
https://github.com/fra589/grbl-Mega-5X/issues/51
https://github.com/fra589/grbl-Mega-5X/issues/48
https://github.com/fra589/grbl-Mega-5X/issues/4
@++;
Gauthier.

**Comment by cybertza** [comment]
$23=11
Seems to have fixed this for me:
`
00001111
'

'
0000AZYX
'

'
00008421
`
