### ISSUE TITLE
Pinout Diagram for Arduino Mega 2560

### ISSUE THREAD

**Issue by karoria** [fra589/grbl-Mega-5X#63]
Hello All...
I have just seen the pinout diagram of grbl-Mega-5X which seems to be of other board not Mega as the footprint and pin locations are not matching. Can anyone please post a good pinout diagram for Mega?
Regards,
Ravi

**Comment by fra589** [comment]
Hi @karoria,  
The pinout diagram is for the RAMPS 1.4+ shield. the name of corresponding Arduino Mega pin is writed in parenthesis on the drawing, and in the text.
@++;  
Gauthier.

**Comment by karoria** [comment]
Got it. Thanks.
