### ISSUE TITLE
CAM tools

### ISSUE THREAD

**Issue by kb-** [fra589/grbl-Mega-5X#64]
Hi,

Could you provide a list of tested CAM tools for 5 axis g-code generation for grbl-Mega-5X? Which ones would you recommend the most?

**Comment by fra589** [comment]
Hi @kb-  
Actually, I don't have tested any CAM tools for 5 axis.  
All the 5 axis test I made for grbl-Mega-5X are writed with my hands.  
I hope FreeCAD will be able to handle it soon, but actually, only the 4th axis is in the development tube.  
It seems than Fusion 360 is able to do it, but I never tested it, and I don't kow the status of Fusion 360 grbl's postprocessor.  
@++;  
Gauthier.
