### ISSUE TITLE
Mini Router CNC 3018+ configurations grbl error 20

### ISSUE THREAD

**Issue by lenoln** [fra589/grbl-Mega-5X#66]
I buy a mini router CNC 3018+ and install the grbl control (Candle 1.1.7). I used the sample iphonef200.cn for the test, I clicked on the Spindler button and after on the Send button, but I received this error. Can someone help me?
`<img src="https://drive.google.com/file/d/1vv7dDrnh-cBFqNltpm0KBxCCxk7EDlj5/view?usp=sharing" alt="CNC Error">`
this is my log and my configurations:
**[CTRL+X] < Grbl 1.1f ['$' for help]
M3 S1000 < ok
M5 < ok
M3 S1000 < ok
M5 < ok
M3 S1000 < ok
M5 < ok
F1000 < ok
M3 S1000 < ok
M5 < ok
$C < [MSG:Enabled]
ok
M3 S1000 < ok
[CTRL+X] < Grbl 1.1f ['$' for help]
G21G53G90X0Y0Z0 < ok
G21G92X0Y2.14748E+06Z-2.14748E+06 < error:20
G54 G17 G21 G90 G94 M9 T0 < ok
S1000 < ok
$$ < $0=10
$1=25
$2=0
$3=5
$4=0
$5=0
$6=0
$10=1
$11=0.010
$12=0.002
$13=0
$20=0
$21=0
$22=0
$23=0
$24=25.000
$25=500.000
$26=250
$27=1.000
$30=1000
$31=0
$32=0
$100=800.000
$101=800.000
$102=800.000
$110=800.000
$111=800.000
$112=500.000
$120=10.000
$121=10.000
$122=10.000
$130=200.000
$131=200.000
$132=200.000
ok**

**Comment by fra589** [comment]
Hi @lenoln,  
The 20 error code seems that you send unsupported or invalid g-code command.  
For your case, is the xxxE+xx exponetial number format that is not supported.  
You can see error significance here :  
https://github.com/fra589/grbl-Mega-5X/blob/edge/doc/csv/error_codes_en_US.csv  
@++;
Gauthier.  
--- Seek and you shall find. ---
