### ISSUE TITLE
TMC Driver support

### ISSUE THREAD

**Issue by jnowak1054** [fra589/grbl-Mega-5X#75]
Not an issue, but an enhancement question. I have quite a few tmc2209's and currently plan on using the tmc's diagnostic pin to emulate a form of sensor-less homing. Has there been any work or plans to implement more Trinamic driver support in grbl-Mega-5x? I have a total of 15 axis spread across 3 grbl5x boards; effectively the system runs each axis back and forth from almost physical endstop to almost physical endstop,  in my case it would be very nice to be able to find home and physical travel limits without all the switches.

**Comment by fra589** [comment]
Hi @jnowak1054,
There is no plan for this.
Grbl need to stay optimized and lightweight in his code...
To save the number of limit switch sensors, you can share the switchs between axis. 
In config.h, you can see this comment at homing definition :  
```
// NOTE: The homing cycle is designed to allow sharing of limit pins, if the axes are not in the same
// cycle, but this requires some pin settings changes in cpu_map.h file. For example, the default homing
// cycle can share the Z limit pin with either X or Y limit pins, since they are on different cycles.
// By sharing a pin, this frees up a precious IO pin for other purposes. In theory, all axes limit pins
// may be reduced to one pin, if all axes are homed with seperate cycles, or vice versa, all three axes
// on separate pin, but homed in one cycle. Also, it should be noted that the function of hard limits
// will not be affected by pin sharing.
```
@++;
Gauthier.
