### ISSUE TITLE
Using 4th and 5th axis without ramps, pin conflict?

### ISSUE THREAD

**Issue by tristanryerparke** [fra589/grbl-Mega-5X#78]
I am trying to use mega-5x with an existing machine that I have built 4th and 5th axis for. the machine uses a custom mega shield that I am making. I want to use the CPU_MAP_2560_INITIAL pin mapping, but the definition for that mapping in cpu_map.h does not show pin numbers for the 4th and 5th axis step/dir pins. If I use the pin numbers from CPU_MAP_2560_RAMPS_BOARD pin 26 is a conflict. Please let me know what I should do. Thanks.

**Comment by jwig22** [comment]
Did you figure out how to remap the pins?
