### ISSUE TITLE
enhancement settings for PPI (pulses per inch) for laser mode

### ISSUE THREAD

**Issue by sinfocomp** [fra589/grbl-Mega-5X#81]
is it possible to add pulses per inch to the laser pwm ?

this helps to process much betther some materials
a lower PPI helps cut wood without charing and a higher ppi gets acrylic edges polished

**Comment by fra589** [comment]
Hi @sinfocomp,  
  
I'm affraid no. On arduino, the PWM frequency is fixed (can be changed but not so easy), it is the  fraction of the time the signal is on (the duty cycle) wich can be varied between 0 and 100%.  
See here for more infos:  
https://www.arduino.cc/en/Tutorial/SecretsOfArduinoPWM  

@++;  
Gauthier.
