### ISSUE TITLE
How do I remap the pins for a different Mega Shield?

### ISSUE THREAD

**Issue by jwig22** [fra589/grbl-Mega-5X#83]
I would like to modify the pinout to fit a shield I have from Eccentric Workshop, but I don't understand how the pinouts are defined in cpu_map.h. I want to use the RAMPS 1.4 option for having 3 or more axes, but need to use the pinout from the INITIAL and include pin definitions for a cloned axis and max/min limits. Can you help me understand the naming convention for the pins or direct me to readings that would help me understand the DDR, PORT, and PINS bits? I need to understand how the pin locations are grouped into DDRA, DDRB, DDRC, etc. 

Thanks for any guidance given.

**Comment by fra589** [comment]
Hi @jwig22,  
I have just added a new wiki page to reply to this mostly asked question:  
https://github.com/fra589/grbl-Mega-5X/wiki/Pinout-mapping-in-cpu_map.h  
  
@++;  
Gauthier.
