### ISSUE TITLE
Grbl error: 20 When you click move A axis or B axis

### ISSUE THREAD

**Issue by ngocphuong7986** [fra589/grbl-Mega-5X#86]
![error 20](https://user-images.githubusercontent.com/46087121/69889452-9a326b00-1323-11ea-8bc5-a6554dd42c1e.jpg)

Hello. I get an error when I move the A axis or B axis, the error message is 20. Please tell me how to fix it. Thank you

**Comment by fra589** [comment]
Hi @ngocphuong7986,  
This strange, it work well for me:
![G1A](https://user-images.githubusercontent.com/19529154/69915932-fb0d9080-1454-11ea-8af0-2f15a5c2cfea.png)
  
Can you post the result of $I and $$ grbl commands?

@++;
Gauthier.

**Comment by fra589** [comment]
No reply for more than 2 weeks... I imagine that this is no longer a problem.
