### ISSUE TITLE
Request, Feature THC inputs for proma 150 and others

### ISSUE THREAD

**Issue by sinfocomp** [fra589/grbl-Mega-5X#89]
Could it be posible to add torch up, torch down inputs to move at max speed the Z axis up or down ? for plasma auto height control?

**Comment by fra589** [comment]
Wy not to use G0 Z... ? This move the Z axis at max speed.

**Comment by sinfocomp** [comment]
But it needs to be adjusted on the fly while cutting to compensate for
sheet metal warping

**Comment by fra589** [comment]
Hi @sinfocomp,  
At first glance, I do not see any easy possibility to implement this functionality without deeply questioning the architecture of Grbl.  
If I had to realize that, I would prefer to add an independent hardware system.  
I'm sorry, but I prefer to focus on features and performance related to Grbl's core business of milling.  
@++;  
Gauthier.
