### ISSUE TITLE
pin order

### ISSUE THREAD

**Issue by saeed477** [fra589/grbl-Mega-5X#9]
1.Can you tell me pins numbers I cant find limit switch pin number. I use it without RAMPS shield .
2.I have windows 7 32 bit on my computer so i cant  install your grbl controller, if you have time please build   
  32 bit version.
thanks, I have no problem and I sorry I cant donate it because I live in Iran.

**Comment by fra589** [comment]
Hi @saeed477,  
The pin numbers are defined in the file cpu_maps.h. Description of standard mapping is here : https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout  
Arduino pin number in ( ) on the drawing.  
I still have to update the description for the 6-axis version, but it's ok for 5 axes.  
Sorry, but I haven't 32bits Windows system to build the cn5X 32bits binary version. You can use directly the Python CN5X software by installing Python 3, PyQT5 and PyQT5-QtSerialPort on your Windows box.  
@++;  
Gauthier.

**Comment by luisluna2** [comment]
Hello again @fra589 
Long time out of this project.
So sorry, but I have some questions:

1.- How desactivate homming cicle for only use 3 axis?
2.- How modify code for have D8, D9 and D10 like 1 and 0 (ON OFF outputs)?

Thank you for your comments!!!

**Comment by luisluna2** [comment]
Dear, one question more: 

3.- How modify the code for use 3 relays outputs and one 0 to 5V PWM?

**Comment by luisluna2** [comment]
In resume, I need use:

3 Axis (one eslave  for Y axis), 3 relays 5V outputs and 1 0-5V PWM.

Could help me friend?

**Comment by fra589** [comment]
Hi @luisluna2,

> 3 Axis (one eslave for Y axis)  

In Config.h:
`#define N_AXIS 4`  
`#define AXIS_1_NAME 'X'`  
`#define AXIS_2_NAME 'Y'`  
`#define AXIS_3_NAME 'Y'`  
`#define AXIS_4_NAME 'Z'`  
  
> use 3 relays outputs and one 0 to 5V PWM?  

D8 and D9 are 0/12v outputs, this is RAMPS hardware dependant,  
D10 is PWM 12v output (also RAMPS hardware dependant), max value defined in cpu_map.h :  
`#define SPINDLE_PWM_MAX_VALUE     1024.0`  
  
> desactivate homming cicle for only use 3 axis?  

Homing cycle is defined in config.h, for 3 axis + y cloned (as the example above):  
`#if N_AXIS == 4 // 4 axis : homing`  
`  #define HOMING_CYCLE_0 (1<<AXIS_4) // Home 4th axis (Z)`  
`  #define HOMING_CYCLE_1 (1<<AXIS_1) // Home X axis`  
`  #define HOMING_CYCLE_2 ((1<<AXIS_2) |  (1<<AXIS_3)) // Home the two Y axis at the same time`  
  
Hope this help you,  
  
@++;
Gauthier.

**Comment by luisluna2** [comment]
@fra589 not can be configure for PWM 0V to 5V?

**Comment by luisluna2** [comment]
Understand friend, one question more, but first you need check this link: [http://www.cnc-club.ru/forum/viewtopic.php?f=151&t=7459&p=260998#p260998](url)

This is ecxatly that I wanna do, put Relays OutPuts. The problem is that you VErsion is GRBL 1.1 and this is 0.9, then I don't undertand how add this process to actual GRBL 5Axis.

The pins that can use with out problems:
D37
D35
D33
D31

Then, how can add this funcion for Relay Outputs?

This is the files modify in the GRBL of the link (seach work "*PO*"): 
![image](https://user-images.githubusercontent.com/38824145/44693578-97fda480-aa2e-11e8-8ce8-dd424e6af5b4.png)

The result will be like this:
![relay](https://user-images.githubusercontent.com/38824145/44693600-caa79d00-aa2e-11e8-8626-59ea165b0d0c.png)

**Comment by fra589** [comment]
Hi @luisluna2,  

Thay you whant requires a lot of work that I can not do for you.  

I can just give you the starting point: 
Try to duplicate the code used for one coolant type (M7 or M8):  
- Duplicate with a new chosen name port & bit defines in cpu_map.h,  
- Duplicate the M7 (or M8) analysis code in gcode.c (case 'M':...) to create your new M* command,  
- Create new functions like those defined in coolant_control.h / coolant_control.c to make the job.

Heaven helps those who help themselves...

@++;
Gauthier.

**Comment by luisluna2** [comment]
Working now... Thank you @fra589

**Comment by luisluna2** [comment]
ALL IS COPY AND MODIFY BUT:

Arduino:1.8.5 (Windows 7), Tarjeta:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from E:\arduino-1.8.5\libraries\grbl/config.h:31:0,

                 from C:\Users\AL\AppData\Local\Temp\arduino_modified_sketch_154373\sketch_aug28a.ino:1:

E:\arduino-1.8.5\libraries\grbl/grbl.h:70:4: error: #error "Required HOMING_CYCLE_0 not defined."

   #error "Required HOMING_CYCLE_0 not defined."

    ^

E:\arduino-1.8.5\libraries\grbl/grbl.h:98:4: error: #error "WCO refresh must be greater than one."

   #error "WCO refresh must be greater than one."

    ^

E:\arduino-1.8.5\libraries\grbl/grbl.h:101:4: error: #error "Override refresh must be greater than zero."

   #error "Override refresh must be greater than zero."

    ^

Se encontraron múltiples librerías para "Servo.h"
Usado: C:\Users\AL\Documents\Arduino\libraries\Servo
 No usado: E:\arduino-1.8.5\libraries\Servo
exit status 1
Error compilando para la tarjeta Arduino/Genuino Mega or Mega 2560.

**Comment by luisluna2** [comment]
I have problems for programing in "coolant_control.c".

in the moment 3 relay outputs is done, but the 3th relay "M66" start only when the 4th relay si activate "M68". And other proble is when enter "M9" desactivate all relays, I don't like this effect.

Could Help me?

**Comment by luisluna2** [comment]
Hi @fra589 2 realys Extra add with out problems, but when add 2 more, the joggin is paused.

Then I have a question, how make 2 PWM with D8 and D9?

**Comment by CozyDama** [comment]
Hello @luisluna2 

I am trying to do something similar! Could you show me what you did in order to get your system working? 

Also @fra589  thank you for this amazing software :) 
Thank you!
