### ISSUE TITLE
Pinout without a rampsboard

### ISSUE THREAD

**Issue by crkie** [fra589/grbl-Mega-5X#93]
Grbl-Mega-5x is perfect for a ramps board. An additional pinout for external stepper drivers with all 5 axes would be great. Maybe the step and dir pins from 22 to 32?

Would this be possible?

Greetings 
Rudi

**Comment by RaphaelDives** [comment]
Hello crkie,
you can change everything you like in the "cpu_map.h" file. 
Imho the best solution would be to define a new board. 
But there are already attempts for alternative pinouts, when I remember right.
Cheers
Raphael

This could be of interest:
https://github.com/fra589/grbl-Mega-5X/wiki/Pinout-mapping-in-cpu_map.h
and here: https://github.com/fra589/grbl-Mega-5X/issues/38

**Comment by crkie** [comment]
Hello Raphael, 
thanks for the link. I am not a C programmer and cannot program a new board. But I can now find the pins. Maybe I'll get on with it.
Cheers
Rudi
