### ISSUE TITLE
4 Linear axis version of Mega 5X

### ISSUE THREAD

**Issue by GrblGru** [fra589/grbl-Mega-5X#99]
Hi Gauthier,

I finally got the time to do the changes for a 4 linear axis version of Mega 5X.
Thanks again for your help. :)

Most users just want to flash the hex file to the Mega with XLoader.
My question now is whether I may provide the HEX file on my website for download.
Or what is the best way to do that ? What is your recommendation ?

**Comment by fra589** [comment]
Hi @GrblGru,  
As long as you respect the Grbl license (GNU GPL v3), you can redistribute Grbl on your own site.
However, I think it is much better to educate users to understand and do things for themselves than to provide them all done and they do not understand the ins and outs of what they have. The version provided will be for a single standard configuration and will not be able to adapt with finesse to the need and to the particular case as does the full version which we compile by managing all the parameters.
In addition, Grbl-Mega-5X will continue to evolve (bug fixes, new features, ...) which will require you to also perform the update work, it seems tedious and unnecessary to do this work in duplicate.
It seems to me much more effective to explain how to do things to achieve the expected result, that's what I did with you, and now, I think you are able to do it again for other different cases and even able to explain it to others! :-)
Knowledge is only worthwhile if it is shared.
@++;
Gauthier.
